/* tslint:disable */
/* eslint-disable */
/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Auth
 */
export interface Auth {
    /**
     * 
     * @type {string}
     * @memberof Auth
     */
    readonly oauth2_auth_url: string;
    /**
     * 
     * @type {string}
     * @memberof Auth
     */
    readonly oauth2_token_url: string;
    /**
     * 
     * @type {boolean}
     * @memberof Auth
     */
    readonly http_basic_supported: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof Auth
     */
    readonly supported_oauth2_flows: Array<string>;
}

export function AuthFromJSON(json: any): Auth {
    return AuthFromJSONTyped(json, false);
}

export function AuthFromJSONTyped(json: any, ignoreDiscriminator: boolean): Auth {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'oauth2_auth_url': json['oauth2_auth_url'],
        'oauth2_token_url': json['oauth2_token_url'],
        'http_basic_supported': json['http_basic_supported'],
        'supported_oauth2_flows': json['supported_oauth2_flows'],
    };
}

export function AuthToJSON(value?: Auth | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

