/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BcfProject
 */
export interface BcfProject {
    /**
     * 
     * @type {number}
     * @memberof BcfProject
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof BcfProject
     */
    readonly projectId: string;
    /**
     * Name of the project
     * @type {string}
     * @memberof BcfProject
     */
    name: string;
}

export function BcfProjectFromJSON(json: any): BcfProject {
    return BcfProjectFromJSONTyped(json, false);
}

export function BcfProjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): BcfProject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'projectId': json['project_id'],
        'name': json['name'],
    };
}

export function BcfProjectToJSON(value?: BcfProject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

