/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum CheckerStatusEnum {
    C = 'C',
    P = 'P',
    E = 'E'
}

export function CheckerStatusEnumFromJSON(json: any): CheckerStatusEnum {
    return CheckerStatusEnumFromJSONTyped(json, false);
}

export function CheckerStatusEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckerStatusEnum {
    return json as CheckerStatusEnum;
}

export function CheckerStatusEnumToJSON(value?: CheckerStatusEnum | null): any {
    return value as any;
}

