/* tslint:disable */
/* eslint-disable */
/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CheckerResultRequest
 */
export interface CheckerResultRequest {
    /**
     * 
     * @type {string}
     * @memberof CheckerResultRequest
     */
    status?: CheckerResultRequestStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof CheckerResultRequest
     */
    result?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CheckerResultRequest
     */
    collisions?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CheckerResultRequest
     */
    error_detail?: string;
}

/**
* @export
* @enum {string}
*/
export enum CheckerResultRequestStatusEnum {
    C = 'C',
    P = 'P',
    E = 'E'
}

export function CheckerResultRequestFromJSON(json: any): CheckerResultRequest {
    return CheckerResultRequestFromJSONTyped(json, false);
}

export function CheckerResultRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckerResultRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': !exists(json, 'status') ? undefined : json['status'],
        'result': !exists(json, 'result') ? undefined : json['result'],
        'collisions': !exists(json, 'collisions') ? undefined : json['collisions'],
        'error_detail': !exists(json, 'error_detail') ? undefined : json['error_detail'],
    };
}

export function CheckerResultRequestToJSON(value?: CheckerResultRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'result': value.result,
        'collisions': value.collisions,
        'error_detail': value.error_detail,
    };
}

