/* tslint:disable */
/* eslint-disable */
/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    RulesetRequest,
    RulesetRequestFromJSON,
    RulesetRequestFromJSONTyped,
    RulesetRequestToJSON,
} from './RulesetRequest';

/**
 * Adds nested create feature
 * @export
 * @interface CheckPlanRequest
 */
export interface CheckPlanRequest {
    /**
     * 
     * @type {string}
     * @memberof CheckPlanRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CheckPlanRequest
     */
    description?: string | null;
    /**
     * 
     * @type {Array<RulesetRequest>}
     * @memberof CheckPlanRequest
     */
    rulesets?: Array<RulesetRequest>;
}

export function CheckPlanRequestFromJSON(json: any): CheckPlanRequest {
    return CheckPlanRequestFromJSONTyped(json, false);
}

export function CheckPlanRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckPlanRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'rulesets': !exists(json, 'rulesets') ? undefined : ((json['rulesets'] as Array<any>).map(RulesetRequestFromJSON)),
    };
}

export function CheckPlanRequestToJSON(value?: CheckPlanRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'rulesets': value.rulesets === undefined ? undefined : ((value.rulesets as Array<any>).map(RulesetRequestToJSON)),
    };
}

