/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CheckerStatusEnum,
    CheckerStatusEnumFromJSON,
    CheckerStatusEnumFromJSONTyped,
    CheckerStatusEnumToJSON,
} from './';

/**
 * 
 * @export
 * @interface CheckerResult
 */
export interface CheckerResult {
    /**
     * 
     * @type {number}
     * @memberof CheckerResult
     */
    readonly id: number;
    /**
     * 
     * @type {CheckerStatusEnum}
     * @memberof CheckerResult
     */
    status?: CheckerStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof CheckerResult
     */
    result?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CheckerResult
     */
    collisions?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof CheckerResult
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof CheckerResult
     */
    readonly updatedAt: Date;
}

export function CheckerResultFromJSON(json: any): CheckerResult {
    return CheckerResultFromJSONTyped(json, false);
}

export function CheckerResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckerResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': !exists(json, 'status') ? undefined : CheckerStatusEnumFromJSON(json['status']),
        'result': !exists(json, 'result') ? undefined : json['result'],
        'collisions': !exists(json, 'collisions') ? undefined : json['collisions'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function CheckerResultToJSON(value?: CheckerResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': CheckerStatusEnumToJSON(value.status),
        'result': value.result,
        'collisions': value.collisions,
    };
}


