/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DirectionRequest,
    DirectionRequestFromJSON,
    DirectionRequestFromJSONTyped,
    DirectionRequestToJSON,
} from './DirectionRequest';
import {
    PointRequest,
    PointRequestFromJSON,
    PointRequestFromJSONTyped,
    PointRequestToJSON,
} from './PointRequest';

/**
 * Adds nested create feature
 * @export
 * @interface ClippingPlaneRequest
 */
export interface ClippingPlaneRequest {
    /**
     * 
     * @type {PointRequest}
     * @memberof ClippingPlaneRequest
     */
    location: PointRequest;
    /**
     * 
     * @type {DirectionRequest}
     * @memberof ClippingPlaneRequest
     */
    direction: DirectionRequest;
}

export function ClippingPlaneRequestFromJSON(json: any): ClippingPlaneRequest {
    return ClippingPlaneRequestFromJSONTyped(json, false);
}

export function ClippingPlaneRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClippingPlaneRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'location': PointRequestFromJSON(json['location']),
        'direction': DirectionRequestFromJSON(json['direction']),
    };
}

export function ClippingPlaneRequestToJSON(value?: ClippingPlaneRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'location': PointRequestToJSON(value.location),
        'direction': DirectionRequestToJSON(value.direction),
    };
}

