/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum CloudRoleEnum {
    NUMBER_100 = 100,
    NUMBER_50 = 50
}

export function CloudRoleEnumFromJSON(json: any): CloudRoleEnum {
    return CloudRoleEnumFromJSONTyped(json, false);
}

export function CloudRoleEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): CloudRoleEnum {
    return json as CloudRoleEnum;
}

export function CloudRoleEnumToJSON(value?: CloudRoleEnum | null): any {
    return value as any;
}

