/* tslint:disable */
/* eslint-disable */
/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CloudRequest
 */
export interface CloudRequest {
    /**
     * Name of the cloud
     * @type {string}
     * @memberof CloudRequest
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof CloudRequest
     */
    organization_id?: number;
    /**
     * 
     * @type {Blob}
     * @memberof CloudRequest
     */
    image?: Blob | null;
}

export function CloudRequestFromJSON(json: any): CloudRequest {
    return CloudRequestFromJSONTyped(json, false);
}

export function CloudRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CloudRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'organization_id': !exists(json, 'organization_id') ? undefined : json['organization_id'],
        'image': !exists(json, 'image') ? undefined : json['image'],
    };
}

export function CloudRequestToJSON(value?: CloudRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'organization_id': value.organization_id,
        'image': value.image,
    };
}

