/* tslint:disable */
/* eslint-disable */
/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Component(id, ifc_guid, originating_system, authoring_tool_id, components_set, coloring, visibility)
 * @export
 * @interface Component
 */
export interface Component {
    /**
     * 
     * @type {string}
     * @memberof Component
     */
    ifcGuid?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Component
     */
    originatingSystem?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Component
     */
    authoringToolId?: string | null;
}

export function ComponentFromJSON(json: any): Component {
    return ComponentFromJSONTyped(json, false);
}

export function ComponentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Component {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ifcGuid': !exists(json, 'ifc_guid') ? undefined : json['ifc_guid'],
        'originatingSystem': !exists(json, 'originating_system') ? undefined : json['originating_system'],
        'authoringToolId': !exists(json, 'authoring_tool_id') ? undefined : json['authoring_tool_id'],
    };
}

export function ComponentToJSON(value?: Component | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ifc_guid': value.ifcGuid,
        'originating_system': value.originatingSystem,
        'authoring_tool_id': value.authoringToolId,
    };
}


