/* tslint:disable */
/* eslint-disable */
/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateBuildingByNameRequest
 */
export interface CreateBuildingByNameRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateBuildingByNameRequest
     */
    name: string | null;
}

export function CreateBuildingByNameRequestFromJSON(json: any): CreateBuildingByNameRequest {
    return CreateBuildingByNameRequestFromJSONTyped(json, false);
}

export function CreateBuildingByNameRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBuildingByNameRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function CreateBuildingByNameRequestToJSON(value?: CreateBuildingByNameRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

