/* tslint:disable */
/* eslint-disable */
/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DocumentText
 */
export interface DocumentText {
    /**
     * 
     * @type {number}
     * @memberof DocumentText
     */
    readonly id: number;
    /**
     * The full text representation of a document if the feature is enabled and the file format supported
     * @type {string}
     * @memberof DocumentText
     */
    text?: string | null;
    /**
     * * `english` - english
     * * `spanish` - spanish
     * * `french` - french
     * * `italian` - italian
     * * `german` - german
     * @type {string}
     * @memberof DocumentText
     */
    language?: DocumentTextLanguageEnum;
}

/**
* @export
* @enum {string}
*/
export enum DocumentTextLanguageEnum {
    English = 'english',
    Spanish = 'spanish',
    French = 'french',
    Italian = 'italian',
    German = 'german',
    Null = 'null'
}

export function DocumentTextFromJSON(json: any): DocumentText {
    return DocumentTextFromJSONTyped(json, false);
}

export function DocumentTextFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentText {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'text': !exists(json, 'text') ? undefined : json['text'],
        'language': !exists(json, 'language') ? undefined : json['language'],
    };
}

export function DocumentTextToJSON(value?: DocumentText | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'text': value.text,
        'language': value.language,
    };
}

