/* tslint:disable */
/* eslint-disable */
/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Tag,
    TagFromJSON,
    TagFromJSONTyped,
    TagToJSON,
} from './Tag';
import {
    User,
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';
import {
    Visa,
    VisaFromJSON,
    VisaFromJSONTyped,
    VisaToJSON,
} from './Visa';

/**
 * 
 * @export
 * @interface Document
 */
export interface Document {
    /**
     * 
     * @type {number}
     * @memberof Document
     */
    readonly id: number;
    /**
     * 
     * @type {number}
     * @memberof Document
     */
    parent_id?: number | null;
    /**
     * 
     * @type {User}
     * @memberof Document
     */
    readonly created_by: User | null;
    /**
     * 
     * @type {number}
     * @memberof Document
     */
    readonly project: number;
    /**
     * Shown name of the file
     * @type {string}
     * @memberof Document
     */
    name: string;
    /**
     * Full name of the file
     * @type {string}
     * @memberof Document
     */
    file_name?: string;
    /**
     * Description of the file
     * @type {string}
     * @memberof Document
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Document
     */
    file: string;
    /**
     * Size of the file.
     * @type {number}
     * @memberof Document
     */
    size?: number | null;
    /**
     * 
     * @type {Array<Tag>}
     * @memberof Document
     */
    readonly tags: Array<Tag>;
    /**
     * 
     * @type {Array<Visa>}
     * @memberof Document
     */
    readonly visas: Array<Visa>;
    /**
     * Creation date
     * @type {Date}
     * @memberof Document
     */
    readonly created_at: Date;
    /**
     * Date of the last update
     * @type {Date}
     * @memberof Document
     */
    readonly updated_at: Date;
    /**
     * 
     * @type {number}
     * @memberof Document
     */
    readonly model_id: number | null;
    /**
     * Model's type. Values can be IFC, DWG, DXF, GLTF, PDF, JPEG, PNG, OBJ, DAE, BFX
     * @type {string}
     * @memberof Document
     */
    readonly model_type: DocumentModelTypeEnum;
    /**
     * DEPRECATED: Use 'model_id' instead.
     * @type {number}
     * @memberof Document
     */
    readonly ifc_id: number | null;
    /**
     * Aggregate of group user permissions and folder default permission
     * @type {number}
     * @memberof Document
     */
    readonly user_permission: DocumentUserPermissionEnum;
    /**
     * Document is a head of version or is owned by another document
     * @type {boolean}
     * @memberof Document
     */
    readonly is_head_version: boolean;
}

/**
* @export
* @enum {string}
*/
export enum DocumentModelTypeEnum {
    Ifc = 'IFC',
    Dwg = 'DWG',
    Dxf = 'DXF',
    Gltf = 'GLTF',
    Pdf = 'PDF',
    Jpeg = 'JPEG',
    Png = 'PNG',
    Obj = 'OBJ',
    Dae = 'DAE',
    Bfx = 'BFX',
    Null = 'null'
}/**
* @export
* @enum {string}
*/
export enum DocumentUserPermissionEnum {
    NUMBER_1 = 1,
    NUMBER_50 = 50,
    NUMBER_100 = 100
}

export function DocumentFromJSON(json: any): Document {
    return DocumentFromJSONTyped(json, false);
}

export function DocumentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Document {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'parent_id': !exists(json, 'parent_id') ? undefined : json['parent_id'],
        'created_by': UserFromJSON(json['created_by']),
        'project': json['project'],
        'name': json['name'],
        'file_name': !exists(json, 'file_name') ? undefined : json['file_name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'file': json['file'],
        'size': !exists(json, 'size') ? undefined : json['size'],
        'tags': ((json['tags'] as Array<any>).map(TagFromJSON)),
        'visas': ((json['visas'] as Array<any>).map(VisaFromJSON)),
        'created_at': (new Date(json['created_at'])),
        'updated_at': (new Date(json['updated_at'])),
        'model_id': json['model_id'],
        'model_type': json['model_type'],
        'ifc_id': json['ifc_id'],
        'user_permission': json['user_permission'],
        'is_head_version': json['is_head_version'],
    };
}

export function DocumentToJSON(value?: Document | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'parent_id': value.parent_id,
        'name': value.name,
        'file_name': value.file_name,
        'description': value.description,
        'file': value.file,
        'size': value.size,
    };
}

