/* tslint:disable */
/* eslint-disable */
/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GroupFolderRead,
    GroupFolderReadFromJSON,
    GroupFolderReadFromJSONTyped,
    GroupFolderReadToJSON,
} from './GroupFolderRead';
import {
    LightDocument,
    LightDocumentFromJSON,
    LightDocumentFromJSONTyped,
    LightDocumentToJSON,
} from './LightDocument';
import {
    ShortUser,
    ShortUserFromJSON,
    ShortUserFromJSONTyped,
    ShortUserToJSON,
} from './ShortUser';

/**
 * 
 * @export
 * @interface EditFolder
 */
export interface EditFolder {
    /**
     * DEPRECATED: Use 'nature' instead. Value is "Folder". It is usefull to parse the tree and discriminate folders and files
     * @type {string}
     * @memberof EditFolder
     */
    readonly type: string;
    /**
     * 
     * @type {number}
     * @memberof EditFolder
     */
    parent_id?: number | null;
    /**
     * 
     * @type {number}
     * @memberof EditFolder
     */
    readonly id: number;
    /**
     * List of group permissions
     * @type {Array<GroupFolderRead>}
     * @memberof EditFolder
     */
    readonly groups_permissions: Array<GroupFolderRead>;
    /**
     * Date of the last update
     * @type {Date}
     * @memberof EditFolder
     */
    readonly updated_at: Date;
    /**
     * Permission for a Folder
     * 
     * * `1` - denied
     * * `50` - read_only
     * * `100` - read_write
     * @type {number}
     * @memberof EditFolder
     */
    default_permission?: EditFolderDefaultPermissionEnum;
    /**
     * 
     * @type {ShortUser}
     * @memberof EditFolder
     */
    readonly created_by: ShortUser | null;
    /**
     * Creation date
     * @type {Date}
     * @memberof EditFolder
     */
    readonly created_at: Date;
    /**
     * Aggregate of group user permissions and folder default permission
     * @type {number}
     * @memberof EditFolder
     */
    readonly user_permission: EditFolderUserPermissionEnum;
    /**
     * Value is "Folder". It is usefull to parse the tree and discriminate folders and files
     * @type {string}
     * @memberof EditFolder
     */
    readonly nature: string;
    /**
     * Name of the folder
     * @type {string}
     * @memberof EditFolder
     */
    name: string;
    /**
     * Return document with naming conflict. This is only set when you move a folder
     * @type {Array<LightDocument>}
     * @memberof EditFolder
     */
    readonly conflicting_documents: Array<LightDocument>;
}

/**
* @export
* @enum {string}
*/
export enum EditFolderDefaultPermissionEnum {
    NUMBER_1 = 1,
    NUMBER_50 = 50,
    NUMBER_100 = 100
}/**
* @export
* @enum {string}
*/
export enum EditFolderUserPermissionEnum {
    NUMBER_1 = 1,
    NUMBER_50 = 50,
    NUMBER_100 = 100
}

export function EditFolderFromJSON(json: any): EditFolder {
    return EditFolderFromJSONTyped(json, false);
}

export function EditFolderFromJSONTyped(json: any, ignoreDiscriminator: boolean): EditFolder {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'parent_id': !exists(json, 'parent_id') ? undefined : json['parent_id'],
        'id': json['id'],
        'groups_permissions': ((json['groups_permissions'] as Array<any>).map(GroupFolderReadFromJSON)),
        'updated_at': (new Date(json['updated_at'])),
        'default_permission': !exists(json, 'default_permission') ? undefined : json['default_permission'],
        'created_by': ShortUserFromJSON(json['created_by']),
        'created_at': (new Date(json['created_at'])),
        'user_permission': json['user_permission'],
        'nature': json['nature'],
        'name': json['name'],
        'conflicting_documents': ((json['conflicting_documents'] as Array<any>).map(LightDocumentFromJSON)),
    };
}

export function EditFolderToJSON(value?: EditFolder | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'parent_id': value.parent_id,
        'default_permission': value.default_permission,
        'name': value.name,
    };
}

