/* tslint:disable */
/* eslint-disable */
/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EquipmentImageRequest
 */
export interface EquipmentImageRequest {
    /**
     * 
     * @type {Blob}
     * @memberof EquipmentImageRequest
     */
    file: Blob;
}

export function EquipmentImageRequestFromJSON(json: any): EquipmentImageRequest {
    return EquipmentImageRequestFromJSONTyped(json, false);
}

export function EquipmentImageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EquipmentImageRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'file': json['file'],
    };
}

export function EquipmentImageRequestToJSON(value?: EquipmentImageRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'file': value.file,
    };
}

