/* tslint:disable */
/* eslint-disable */
/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FolderNamingConstraintRequest
 */
export interface FolderNamingConstraintRequest {
    /**
     * 
     * @type {number}
     * @memberof FolderNamingConstraintRequest
     */
    constraint_id: number;
    /**
     * 
     * @type {boolean}
     * @memberof FolderNamingConstraintRequest
     */
    recursive: boolean;
}

export function FolderNamingConstraintRequestFromJSON(json: any): FolderNamingConstraintRequest {
    return FolderNamingConstraintRequestFromJSONTyped(json, false);
}

export function FolderNamingConstraintRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FolderNamingConstraintRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'constraint_id': json['constraint_id'],
        'recursive': json['recursive'],
    };
}

export function FolderNamingConstraintRequestToJSON(value?: FolderNamingConstraintRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'constraint_id': value.constraint_id,
        'recursive': value.recursive,
    };
}

