/* tslint:disable */
/* eslint-disable */
/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    FolderGroupPermission,
    FolderGroupPermissionFromJSON,
    FolderGroupPermissionFromJSONTyped,
    FolderGroupPermissionToJSON,
} from './FolderGroupPermission';
import {
    User,
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface FolderWithoutChildren
 */
export interface FolderWithoutChildren {
    /**
     * 
     * @type {number}
     * @memberof FolderWithoutChildren
     */
    readonly id: number;
    /**
     * 
     * @type {number}
     * @memberof FolderWithoutChildren
     */
    parentId?: number | null;
    /**
     * DEPRECATED: Use 'nature' instead. Value is "Folder". It is usefull to parse the tree and discriminate folders and files
     * @type {string}
     * @memberof FolderWithoutChildren
     */
    readonly type: string;
    /**
     * Value is "Folder". It is usefull to parse the tree and discriminate folders and files
     * @type {string}
     * @memberof FolderWithoutChildren
     */
    readonly nature: string;
    /**
     * Name of the folder
     * @type {string}
     * @memberof FolderWithoutChildren
     */
    name: string;
    /**
     * Creation date
     * @type {Date}
     * @memberof FolderWithoutChildren
     */
    readonly createdAt: Date;
    /**
     * Date of the last update
     * @type {Date}
     * @memberof FolderWithoutChildren
     */
    readonly updatedAt: Date;
    /**
     * 
     * @type {User}
     * @memberof FolderWithoutChildren
     */
    readonly createdBy: User | null;
    /**
     * 
     * @type {Array<FolderGroupPermission>}
     * @memberof FolderWithoutChildren
     */
    readonly groupsPermissions: Array<FolderGroupPermission>;
    /**
     * Permission for a Folder
     * @type {number}
     * @memberof FolderWithoutChildren
     */
    defaultPermission?: FolderWithoutChildrenDefaultPermissionEnum;
    /**
     * Aggregate of group user permissions and folder default permission
     * @type {number}
     * @memberof FolderWithoutChildren
     */
    readonly userPermission: FolderWithoutChildrenUserPermissionEnum;
}

/**
* @export
* @enum {string}
*/
export enum FolderWithoutChildrenDefaultPermissionEnum {
    NUMBER_1 = 1,
    NUMBER_50 = 50,
    NUMBER_100 = 100
}/**
* @export
* @enum {string}
*/
export enum FolderWithoutChildrenUserPermissionEnum {
    NUMBER_1 = 1,
    NUMBER_50 = 50,
    NUMBER_100 = 100
}

export function FolderWithoutChildrenFromJSON(json: any): FolderWithoutChildren {
    return FolderWithoutChildrenFromJSONTyped(json, false);
}

export function FolderWithoutChildrenFromJSONTyped(json: any, ignoreDiscriminator: boolean): FolderWithoutChildren {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'parentId': !exists(json, 'parent_id') ? undefined : json['parent_id'],
        'type': json['type'],
        'nature': json['nature'],
        'name': json['name'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'createdBy': UserFromJSON(json['created_by']),
        'groupsPermissions': ((json['groups_permissions'] as Array<any>).map(FolderGroupPermissionFromJSON)),
        'defaultPermission': !exists(json, 'default_permission') ? undefined : json['default_permission'],
        'userPermission': json['user_permission'],
    };
}

export function FolderWithoutChildrenToJSON(value?: FolderWithoutChildren | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'parent_id': value.parentId,
        'name': value.name,
        'default_permission': value.defaultPermission,
    };
}

