/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    FolderPermissionEnum,
    FolderPermissionEnumFromJSON,
    FolderPermissionEnumFromJSONTyped,
    FolderPermissionEnumToJSON,
    GroupRequest,
    GroupRequestFromJSON,
    GroupRequestFromJSONTyped,
    GroupRequestToJSON,
} from './';

/**
 * 
 * @export
 * @interface FolderGroupPermissionRequest
 */
export interface FolderGroupPermissionRequest {
    /**
     * 
     * @type {GroupRequest}
     * @memberof FolderGroupPermissionRequest
     */
    group: GroupRequest;
    /**
     * Group's permission for a folder
     * @type {FolderPermissionEnum}
     * @memberof FolderGroupPermissionRequest
     */
    permission?: FolderPermissionEnum;
}

export function FolderGroupPermissionRequestFromJSON(json: any): FolderGroupPermissionRequest {
    return FolderGroupPermissionRequestFromJSONTyped(json, false);
}

export function FolderGroupPermissionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FolderGroupPermissionRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'group': GroupRequestFromJSON(json['group']),
        'permission': !exists(json, 'permission') ? undefined : FolderPermissionEnumFromJSON(json['permission']),
    };
}

export function FolderGroupPermissionRequestToJSON(value?: FolderGroupPermissionRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'group': GroupRequestToJSON(value.group),
        'permission': FolderPermissionEnumToJSON(value.permission),
    };
}


