/* tslint:disable */
/* eslint-disable */
/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Group,
    GroupFromJSON,
    GroupFromJSONTyped,
    GroupToJSON,
} from './Group';

/**
 * 
 * @export
 * @interface FolderGroupPermission
 */
export interface FolderGroupPermission {
    /**
     * 
     * @type {Group}
     * @memberof FolderGroupPermission
     */
    group: Group;
    /**
     * Group's permission for a folder
     * @type {number}
     * @memberof FolderGroupPermission
     */
    permission?: FolderGroupPermissionPermissionEnum;
}

/**
* @export
* @enum {string}
*/
export enum FolderGroupPermissionPermissionEnum {
    NUMBER_1 = 1,
    NUMBER_50 = 50,
    NUMBER_100 = 100
}

export function FolderGroupPermissionFromJSON(json: any): FolderGroupPermission {
    return FolderGroupPermissionFromJSONTyped(json, false);
}

export function FolderGroupPermissionFromJSONTyped(json: any, ignoreDiscriminator: boolean): FolderGroupPermission {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'group': GroupFromJSON(json['group']),
        'permission': !exists(json, 'permission') ? undefined : json['permission'],
    };
}

export function FolderGroupPermissionToJSON(value?: FolderGroupPermission | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'group': GroupToJSON(value.group),
        'permission': value.permission,
    };
}

