/* tslint:disable */
/* eslint-disable */
/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GeometryPoint
 */
export interface GeometryPoint {
    /**
     * 
     * @type {number}
     * @memberof GeometryPoint
     */
    x: number;
    /**
     * 
     * @type {number}
     * @memberof GeometryPoint
     */
    y: number;
}

export function GeometryPointFromJSON(json: any): GeometryPoint {
    return GeometryPointFromJSONTyped(json, false);
}

export function GeometryPointFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeometryPoint {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'x': json['x'],
        'y': json['y'],
    };
}

export function GeometryPointToJSON(value?: GeometryPoint | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'x': value.x,
        'y': value.y,
    };
}

