/* tslint:disable */
/* eslint-disable */
/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    UserProject,
    UserProjectFromJSON,
    UserProjectFromJSONTyped,
    UserProjectToJSON,
} from './UserProject';

/**
 * 
 * @export
 * @interface Group
 */
export interface Group {
    /**
     * 
     * @type {number}
     * @memberof Group
     */
    readonly id: number;
    /**
     * Full name of the group
     * @type {string}
     * @memberof Group
     */
    name: string;
    /**
     * Short name of the group
     * @type {string}
     * @memberof Group
     */
    short_name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Group
     */
    color?: string | null;
    /**
     * 
     * @type {Array<UserProject>}
     * @memberof Group
     */
    readonly members: Array<UserProject>;
}

export function GroupFromJSON(json: any): Group {
    return GroupFromJSONTyped(json, false);
}

export function GroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): Group {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'short_name': !exists(json, 'short_name') ? undefined : json['short_name'],
        'color': !exists(json, 'color') ? undefined : json['color'],
        'members': ((json['members'] as Array<any>).map(UserProjectFromJSON)),
    };
}

export function GroupToJSON(value?: Group | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'short_name': value.short_name,
        'color': value.color,
    };
}

