/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ExportEnum,
    ExportEnumFromJSON,
    ExportEnumFromJSONTyped,
    ExportEnumToJSON,
} from './ExportEnum';

/**
 * 
 * @export
 * @interface IfcExportRequest
 */
export interface IfcExportRequest {
    /**
     * Exported IFC will include classifications from original IFC file (ORIGINAL), from latest API updates (UPDATED), or won't include classifications(NONE)
     * @type {ExportEnum}
     * @memberof IfcExportRequest
     */
    classifications?: ExportEnum | null;
    /**
     * Exported IFC will include zones from original IFC file (ORIGINAL), from latest API updates (UPDATED), or won't include zones(NONE)
     * @type {ExportEnum}
     * @memberof IfcExportRequest
     */
    zones?: ExportEnum | null;
    /**
     * Exported IFC will include properties from original IFC file (ORIGINAL), from latest API updates (UPDATED), or won't include properties(NONE)
     * @type {ExportEnum}
     * @memberof IfcExportRequest
     */
    properties?: ExportEnum | null;
    /**
     * Exported IFC will include systems from original IFC file (ORIGINAL), from latest API updates (UPDATED), or won't include systems(NONE)
     * @type {ExportEnum}
     * @memberof IfcExportRequest
     */
    systems?: ExportEnum | null;
    /**
     * Exported IFC will include layers from original IFC file (ORIGINAL), from latest API updates (UPDATED), or won't include layers(NONE)
     * @type {ExportEnum}
     * @memberof IfcExportRequest
     */
    layers?: ExportEnum | null;
    /**
     * Exported IFC will include materials from original IFC file (ORIGINAL), from latest API updates (UPDATED), or won't include materials(NONE)
     * @type {ExportEnum}
     * @memberof IfcExportRequest
     */
    materials?: ExportEnum | null;
    /**
     * Exported IFC will include attributes from original IFC file (ORIGINAL), from latest API updates (UPDATED), or won't include attributes(NONE)
     * @type {ExportEnum}
     * @memberof IfcExportRequest
     */
    attributes?: ExportEnum | null;
    /**
     * Exported IFC will include the structure from original IFC file (ORIGINAL), from latest API updates (UPDATED), or won't include structure(NONE)
     * @type {ExportEnum}
     * @memberof IfcExportRequest
     */
    structure?: ExportEnum | null;
    /**
     * Exported IFC will only have those elements. If omitted, all elements will be exported
     * @type {Array<string>}
     * @memberof IfcExportRequest
     */
    uuids?: Array<string>;
    /**
     * The name of the exported IFC file. It MUST end with .ifc or the exported file won't be processed by BIMData
     * @type {string}
     * @memberof IfcExportRequest
     */
    fileName: string;
}

export function IfcExportRequestFromJSON(json: any): IfcExportRequest {
    return IfcExportRequestFromJSONTyped(json, false);
}

export function IfcExportRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): IfcExportRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'classifications': !exists(json, 'classifications') ? undefined : ExportEnumFromJSON(json['classifications']),
        'zones': !exists(json, 'zones') ? undefined : ExportEnumFromJSON(json['zones']),
        'properties': !exists(json, 'properties') ? undefined : ExportEnumFromJSON(json['properties']),
        'systems': !exists(json, 'systems') ? undefined : ExportEnumFromJSON(json['systems']),
        'layers': !exists(json, 'layers') ? undefined : ExportEnumFromJSON(json['layers']),
        'materials': !exists(json, 'materials') ? undefined : ExportEnumFromJSON(json['materials']),
        'attributes': !exists(json, 'attributes') ? undefined : ExportEnumFromJSON(json['attributes']),
        'structure': !exists(json, 'structure') ? undefined : ExportEnumFromJSON(json['structure']),
        'uuids': !exists(json, 'uuids') ? undefined : json['uuids'],
        'fileName': json['file_name'],
    };
}

export function IfcExportRequestToJSON(value?: IfcExportRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'classifications': ExportEnumToJSON(value.classifications),
        'zones': ExportEnumToJSON(value.zones),
        'properties': ExportEnumToJSON(value.properties),
        'systems': ExportEnumToJSON(value.systems),
        'layers': ExportEnumToJSON(value.layers),
        'materials': ExportEnumToJSON(value.materials),
        'attributes': ExportEnumToJSON(value.attributes),
        'structure': ExportEnumToJSON(value.structure),
        'uuids': value.uuids,
        'file_name': value.fileName,
    };
}

