/* tslint:disable */
/* eslint-disable */
/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Ifc(id, creator, document, project, created_at, updated_at, structure_file, systems_file, zones_file, map_file, gltf_file, gltf_with_openings_file, bvh_tree_file, viewer_360_file, xkt_file, world_position, is_demo, errors, warnings, source, update_check_needed, archived, version)
 * @export
 * @interface IfcExport
 */
export interface IfcExport {
    /**
     * Exported IFC will include classifications from original IFC file (ORIGINAL), from latest API updates (UPDATED), or won\'t include classifications(NONE)
     * @type {string}
     * @memberof IfcExport
     */
    classifications?: IfcExportClassificationsEnum;
    /**
     * Exported IFC will include zones from original IFC file (ORIGINAL), from latest API updates (UPDATED), or won\'t include zones(NONE)
     * @type {string}
     * @memberof IfcExport
     */
    zones?: IfcExportZonesEnum;
    /**
     * Exported IFC will include properties from original IFC file (ORIGINAL), from latest API updates (UPDATED), or won\'t include properties(NONE)
     * @type {string}
     * @memberof IfcExport
     */
    properties?: IfcExportPropertiesEnum;
    /**
     * Exported IFC will include systems from original IFC file (ORIGINAL), from latest API updates (UPDATED), or won\'t include systems(NONE)
     * @type {string}
     * @memberof IfcExport
     */
    systems?: IfcExportSystemsEnum;
    /**
     * Exported IFC will include layers from original IFC file (ORIGINAL), from latest API updates (UPDATED), or won\'t include layers(NONE)
     * @type {string}
     * @memberof IfcExport
     */
    layers?: IfcExportLayersEnum;
    /**
     * Exported IFC will include materials from original IFC file (ORIGINAL), from latest API updates (UPDATED), or won\'t include materials(NONE)
     * @type {string}
     * @memberof IfcExport
     */
    materials?: IfcExportMaterialsEnum;
    /**
     * Exported IFC will include attributes from original IFC file (ORIGINAL), from latest API updates (UPDATED), or won\'t include attributes(NONE)
     * @type {string}
     * @memberof IfcExport
     */
    attributes?: IfcExportAttributesEnum;
    /**
     * Exported IFC will include the structure from original IFC file (ORIGINAL), from latest API updates (UPDATED), or won\'t include structure(NONE)
     * @type {string}
     * @memberof IfcExport
     */
    structure?: IfcExportStructureEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof IfcExport
     */
    uuids?: Array<string>;
    /**
     * The name of the exported IFC file. It MUST end with .ifc or the exported file won\'t be processed by BIMData
     * @type {string}
     * @memberof IfcExport
     */
    fileName: string;
}

export function IfcExportFromJSON(json: any): IfcExport {
    return IfcExportFromJSONTyped(json, false);
}

export function IfcExportFromJSONTyped(json: any, ignoreDiscriminator: boolean): IfcExport {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'classifications': !exists(json, 'classifications') ? undefined : json['classifications'],
        'zones': !exists(json, 'zones') ? undefined : json['zones'],
        'properties': !exists(json, 'properties') ? undefined : json['properties'],
        'systems': !exists(json, 'systems') ? undefined : json['systems'],
        'layers': !exists(json, 'layers') ? undefined : json['layers'],
        'materials': !exists(json, 'materials') ? undefined : json['materials'],
        'attributes': !exists(json, 'attributes') ? undefined : json['attributes'],
        'structure': !exists(json, 'structure') ? undefined : json['structure'],
        'uuids': !exists(json, 'uuids') ? undefined : json['uuids'],
        'fileName': json['file_name'],
    };
}

export function IfcExportToJSON(value?: IfcExport | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'classifications': value.classifications,
        'zones': value.zones,
        'properties': value.properties,
        'systems': value.systems,
        'layers': value.layers,
        'materials': value.materials,
        'attributes': value.attributes,
        'structure': value.structure,
        'uuids': value.uuids,
        'file_name': value.fileName,
    };
}

/**
* @export
* @enum {string}
*/
export enum IfcExportClassificationsEnum {
    ORIGINAL = 'ORIGINAL',
    UPDATED = 'UPDATED',
    NONE = 'NONE'
}
/**
* @export
* @enum {string}
*/
export enum IfcExportZonesEnum {
    ORIGINAL = 'ORIGINAL',
    UPDATED = 'UPDATED',
    NONE = 'NONE'
}
/**
* @export
* @enum {string}
*/
export enum IfcExportPropertiesEnum {
    ORIGINAL = 'ORIGINAL',
    UPDATED = 'UPDATED',
    NONE = 'NONE'
}
/**
* @export
* @enum {string}
*/
export enum IfcExportSystemsEnum {
    ORIGINAL = 'ORIGINAL',
    UPDATED = 'UPDATED',
    NONE = 'NONE'
}
/**
* @export
* @enum {string}
*/
export enum IfcExportLayersEnum {
    ORIGINAL = 'ORIGINAL',
    UPDATED = 'UPDATED',
    NONE = 'NONE'
}
/**
* @export
* @enum {string}
*/
export enum IfcExportMaterialsEnum {
    ORIGINAL = 'ORIGINAL',
    UPDATED = 'UPDATED',
    NONE = 'NONE'
}
/**
* @export
* @enum {string}
*/
export enum IfcExportAttributesEnum {
    ORIGINAL = 'ORIGINAL',
    UPDATED = 'UPDATED',
    NONE = 'NONE'
}
/**
* @export
* @enum {string}
*/
export enum IfcExportStructureEnum {
    ORIGINAL = 'ORIGINAL',
    UPDATED = 'UPDATED',
    NONE = 'NONE'
}


