/* tslint:disable */
/* eslint-disable */
/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Ifc(id, creator, document, project, created_at, updated_at, structure_file, systems_file, zones_file, map_file, gltf_file, gltf_with_openings_file, bvh_tree_file, viewer_360_file, xkt_file, world_position, is_demo, errors, warnings, source, update_check_needed, archived)
 * @export
 * @interface IfcFiles
 */
export interface IfcFiles {
    /**
     * 
     * @type {string}
     * @memberof IfcFiles
     */
    readonly structureFile?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IfcFiles
     */
    readonly systemsFile?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IfcFiles
     */
    readonly mapFile?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IfcFiles
     */
    readonly gltfFile?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IfcFiles
     */
    readonly gltfWithOpeningsFile?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IfcFiles
     */
    readonly bvhTreeFile?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IfcFiles
     */
    readonly viewer360File?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IfcFiles
     */
    readonly xktFile?: string | null;
}

export function IfcFilesFromJSON(json: any): IfcFiles {
    return IfcFilesFromJSONTyped(json, false);
}

export function IfcFilesFromJSONTyped(json: any, ignoreDiscriminator: boolean): IfcFiles {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'structureFile': !exists(json, 'structure_file') ? undefined : json['structure_file'],
        'systemsFile': !exists(json, 'systems_file') ? undefined : json['systems_file'],
        'mapFile': !exists(json, 'map_file') ? undefined : json['map_file'],
        'gltfFile': !exists(json, 'gltf_file') ? undefined : json['gltf_file'],
        'gltfWithOpeningsFile': !exists(json, 'gltf_with_openings_file') ? undefined : json['gltf_with_openings_file'],
        'bvhTreeFile': !exists(json, 'bvh_tree_file') ? undefined : json['bvh_tree_file'],
        'viewer360File': !exists(json, 'viewer_360_file') ? undefined : json['viewer_360_file'],
        'xktFile': !exists(json, 'xkt_file') ? undefined : json['xkt_file'],
    };
}

export function IfcFilesToJSON(value?: IfcFiles | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}


