/* tslint:disable */
/* eslint-disable */
/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImportGroupRequest
 */
export interface ImportGroupRequest {
    /**
     * List of group identifiers to import from a project
     * @type {Array<number>}
     * @memberof ImportGroupRequest
     */
    group_ids: Array<number>;
    /**
     * Imported users will be redirected to this uri when they accept the invitation
     * @type {string}
     * @memberof ImportGroupRequest
     */
    redirect_uri: string;
}

export function ImportGroupRequestFromJSON(json: any): ImportGroupRequest {
    return ImportGroupRequestFromJSONTyped(json, false);
}

export function ImportGroupRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImportGroupRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'group_ids': json['group_ids'],
        'redirect_uri': json['redirect_uri'],
    };
}

export function ImportGroupRequestToJSON(value?: ImportGroupRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'group_ids': value.group_ids,
        'redirect_uri': value.redirect_uri,
    };
}

