/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CloudRoleEnum,
    CloudRoleEnumFromJSON,
    CloudRoleEnumFromJSONTyped,
    CloudRoleEnumToJSON,
    InvitationStatusEnum,
    InvitationStatusEnumFromJSON,
    InvitationStatusEnumFromJSONTyped,
    InvitationStatusEnumToJSON,
    NullEnum,
    NullEnumFromJSON,
    NullEnumFromJSONTyped,
    NullEnumToJSON,
    ProjectRoleEnum,
    ProjectRoleEnumFromJSON,
    ProjectRoleEnumFromJSONTyped,
    ProjectRoleEnumToJSON,
} from './';

/**
 * 
 * @export
 * @interface Invitation
 */
export interface Invitation {
    /**
     * 
     * @type {number}
     * @memberof Invitation
     */
    readonly id: number;
    /**
     * 
     * @type {number}
     * @memberof Invitation
     */
    readonly clientId: number;
    /**
     * User will be redirected to this uri when they accept the invitation
     * @type {string}
     * @memberof Invitation
     */
    redirectUri: string;
    /**
     * 
     * @type {string}
     * @memberof Invitation
     */
    cloudName: string;
    /**
     * Role the user will have when they accept the invitation
     * @type {CloudRoleEnum}
     * @memberof Invitation
     */
    cloudRole: CloudRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof Invitation
     */
    projectName?: string;
    /**
     * Role the user will have when they accept the invitation
     * @type {ProjectRoleEnum | NullEnum}
     * @memberof Invitation
     */
    projectRole?: ProjectRoleEnum | NullEnum | null;
    /**
     * email of the user to invite
     * @type {string}
     * @memberof Invitation
     */
    email: string;
    /**
     * 
     *         A: Accepted
     *         D: Denied
     *         P: Pending
     *         
     * @type {InvitationStatusEnum}
     * @memberof Invitation
     */
    status?: InvitationStatusEnum;
    /**
     * OIDC sub of the sender. The original sub from the provider is used instead of the broker sub
     * @type {string}
     * @memberof Invitation
     */
    senderProviderSub?: string;
}

export function InvitationFromJSON(json: any): Invitation {
    return InvitationFromJSONTyped(json, false);
}

export function InvitationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Invitation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'clientId': json['client_id'],
        'redirectUri': json['redirect_uri'],
        'cloudName': json['cloud_name'],
        'cloudRole': CloudRoleEnumFromJSON(json['cloud_role']),
        'projectName': !exists(json, 'project_name') ? undefined : json['project_name'],
        'projectRole': !exists(json, 'project_role') ? undefined : ProjectRoleEnum | NullEnumFromJSON(json['project_role']),
        'email': json['email'],
        'status': !exists(json, 'status') ? undefined : InvitationStatusEnumFromJSON(json['status']),
        'senderProviderSub': !exists(json, 'sender_provider_sub') ? undefined : json['sender_provider_sub'],
    };
}

export function InvitationToJSON(value?: Invitation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'redirect_uri': value.redirectUri,
        'cloud_name': value.cloudName,
        'cloud_role': CloudRoleEnumToJSON(value.cloudRole),
        'project_name': value.projectName,
        'project_role': ProjectRoleEnum | NullEnumToJSON(value.projectRole),
        'email': value.email,
        'status': InvitationStatusEnumToJSON(value.status),
        'sender_provider_sub': value.senderProviderSub,
    };
}


