/* tslint:disable */
/* eslint-disable */
/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LabelRead
 */
export interface LabelRead {
    /**
     * 
     * @type {string}
     * @memberof LabelRead
     */
    label: string;
}

export function LabelReadFromJSON(json: any): LabelRead {
    return LabelReadFromJSONTyped(json, false);
}

export function LabelReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): LabelRead {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'label': json['label'],
    };
}

export function LabelReadToJSON(value?: LabelRead | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'label': value.label,
    };
}


