/* tslint:disable */
/* eslint-disable */
/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Point,
    PointFromJSON,
    PointFromJSONTyped,
    PointToJSON,
} from './Point';

/**
 * Adds nested create feature
 * @export
 * @interface Line
 */
export interface Line {
    /**
     * 
     * @type {Point}
     * @memberof Line
     */
    end_point: Point;
    /**
     * 
     * @type {Point}
     * @memberof Line
     */
    start_point: Point;
}

export function LineFromJSON(json: any): Line {
    return LineFromJSONTyped(json, false);
}

export function LineFromJSONTyped(json: any, ignoreDiscriminator: boolean): Line {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'end_point': PointFromJSON(json['end_point']),
        'start_point': PointFromJSON(json['start_point']),
    };
}

export function LineToJSON(value?: Line | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'end_point': PointToJSON(value.end_point),
        'start_point': PointToJSON(value.start_point),
    };
}

