/* tslint:disable */
/* eslint-disable */
/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    MarketplaceAppImage,
    MarketplaceAppImageFromJSON,
    MarketplaceAppImageFromJSONTyped,
    MarketplaceAppImageToJSON,
} from './MarketplaceAppImage';
import {
    PublicOrganization,
    PublicOrganizationFromJSON,
    PublicOrganizationFromJSONTyped,
    PublicOrganizationToJSON,
} from './PublicOrganization';

/**
 * 
 * @export
 * @interface MarketplaceAppLight
 */
export interface MarketplaceAppLight {
    /**
     * 
     * @type {number}
     * @memberof MarketplaceAppLight
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof MarketplaceAppLight
     */
    name: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof MarketplaceAppLight
     */
    viewer_plugins_urls?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof MarketplaceAppLight
     */
    file?: string | null;
    /**
     * 
     * @type {PublicOrganization}
     * @memberof MarketplaceAppLight
     */
    readonly organization: PublicOrganization | null;
    /**
     * 
     * @type {Array<MarketplaceAppImage>}
     * @memberof MarketplaceAppLight
     */
    readonly images: Array<MarketplaceAppImage>;
}

export function MarketplaceAppLightFromJSON(json: any): MarketplaceAppLight {
    return MarketplaceAppLightFromJSONTyped(json, false);
}

export function MarketplaceAppLightFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarketplaceAppLight {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'viewer_plugins_urls': !exists(json, 'viewer_plugins_urls') ? undefined : json['viewer_plugins_urls'],
        'file': !exists(json, 'file') ? undefined : json['file'],
        'organization': PublicOrganizationFromJSON(json['organization']),
        'images': ((json['images'] as Array<any>).map(MarketplaceAppImageFromJSON)),
    };
}

export function MarketplaceAppLightToJSON(value?: MarketplaceAppLight | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'viewer_plugins_urls': value.viewer_plugins_urls,
        'file': value.file,
    };
}

