/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    MaterialRequest,
    MaterialRequestFromJSON,
    MaterialRequestFromJSONTyped,
    MaterialRequestToJSON,
} from './';

/**
 * 
 * @export
 * @interface MaterialListComponentRequest
 */
export interface MaterialListComponentRequest {
    /**
     * 
     * @type {MaterialRequest}
     * @memberof MaterialListComponentRequest
     */
    material?: MaterialRequest;
}

export function MaterialListComponentRequestFromJSON(json: any): MaterialListComponentRequest {
    return MaterialListComponentRequestFromJSONTyped(json, false);
}

export function MaterialListComponentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MaterialListComponentRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'material': !exists(json, 'material') ? undefined : MaterialRequestFromJSON(json['material']),
    };
}

export function MaterialListComponentRequestToJSON(value?: MaterialListComponentRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'material': MaterialRequestToJSON(value.material),
    };
}


