/* tslint:disable */
/* eslint-disable */
/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelInModelPosition
 */
export interface ModelInModelPosition {
    /**
     * 
     * @type {number}
     * @memberof ModelInModelPosition
     */
    parent_model: number;
    /**
     * Must be an array [x,y,z] of the position of the positioned model in reference model coordinates
     * @type {Array<number>}
     * @memberof ModelInModelPosition
     */
    readonly position: Array<number>;
}

export function ModelInModelPositionFromJSON(json: any): ModelInModelPosition {
    return ModelInModelPositionFromJSONTyped(json, false);
}

export function ModelInModelPositionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelInModelPosition {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'parent_model': json['parent_model'],
        'position': json['position'],
    };
}

export function ModelInModelPositionToJSON(value?: ModelInModelPosition | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'parent_model': value.parent_model,
    };
}

