/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ModelTypeEnum {
    IFC = 'IFC',
    DWG = 'DWG',
    DXF = 'DXF',
    GLTF = 'GLTF',
    PDF = 'PDF',
    JPEG = 'JPEG',
    PNG = 'PNG',
    OBJ = 'OBJ',
    DAE = 'DAE',
    BFX = 'BFX',
    METABUILDING = 'METABUILDING'
}

export function ModelTypeEnumFromJSON(json: any): ModelTypeEnum {
    return ModelTypeEnumFromJSONTyped(json, false);
}

export function ModelTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelTypeEnum {
    return json as ModelTypeEnum;
}

export function ModelTypeEnumToJSON(value?: ModelTypeEnum | null): any {
    return value as any;
}

