/* tslint:disable */
/* eslint-disable */
/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NamingPartsTemplate
 */
export interface NamingPartsTemplate {
    /**
     * 
     * @type {number}
     * @memberof NamingPartsTemplate
     */
    readonly id: number;
    /**
     * Name of the template
     * @type {string}
     * @memberof NamingPartsTemplate
     */
    name: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof NamingPartsTemplate
     */
    elements: Array<string>;
}

export function NamingPartsTemplateFromJSON(json: any): NamingPartsTemplate {
    return NamingPartsTemplateFromJSONTyped(json, false);
}

export function NamingPartsTemplateFromJSONTyped(json: any, ignoreDiscriminator: boolean): NamingPartsTemplate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'elements': json['elements'],
    };
}

export function NamingPartsTemplateToJSON(value?: NamingPartsTemplate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'elements': value.elements,
    };
}

