/* tslint:disable */
/* eslint-disable */
/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DirectionRequest,
    DirectionRequestFromJSON,
    DirectionRequestFromJSONTyped,
    DirectionRequestToJSON,
} from './DirectionRequest';
import {
    PointRequest,
    PointRequestFromJSON,
    PointRequestFromJSONTyped,
    PointRequestToJSON,
} from './PointRequest';

/**
 * Adds nested create feature
 * @export
 * @interface OrthogonalCameraRequest
 */
export interface OrthogonalCameraRequest {
    /**
     * 
     * @type {number}
     * @memberof OrthogonalCameraRequest
     */
    view_to_world_scale: number;
    /**
     * 
     * @type {DirectionRequest}
     * @memberof OrthogonalCameraRequest
     */
    camera_direction: DirectionRequest;
    /**
     * 
     * @type {DirectionRequest}
     * @memberof OrthogonalCameraRequest
     */
    camera_up_vector: DirectionRequest;
    /**
     * 
     * @type {PointRequest}
     * @memberof OrthogonalCameraRequest
     */
    camera_view_point: PointRequest;
}

export function OrthogonalCameraRequestFromJSON(json: any): OrthogonalCameraRequest {
    return OrthogonalCameraRequestFromJSONTyped(json, false);
}

export function OrthogonalCameraRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrthogonalCameraRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'view_to_world_scale': json['view_to_world_scale'],
        'camera_direction': DirectionRequestFromJSON(json['camera_direction']),
        'camera_up_vector': DirectionRequestFromJSON(json['camera_up_vector']),
        'camera_view_point': PointRequestFromJSON(json['camera_view_point']),
    };
}

export function OrthogonalCameraRequestToJSON(value?: OrthogonalCameraRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'view_to_world_scale': value.view_to_world_scale,
        'camera_direction': DirectionRequestToJSON(value.camera_direction),
        'camera_up_vector': DirectionRequestToJSON(value.camera_up_vector),
        'camera_view_point': PointRequestToJSON(value.camera_view_point),
    };
}

