/* tslint:disable */
/* eslint-disable */
/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedProjectAccessTokenRequest
 */
export interface PatchedProjectAccessTokenRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof PatchedProjectAccessTokenRequest
     */
    scopes?: Array<PatchedProjectAccessTokenRequestScopesEnum>;
    /**
     * 
     * @type {Date}
     * @memberof PatchedProjectAccessTokenRequest
     */
    expires_at?: Date;
}

/**
* @export
* @enum {string}
*/
export enum PatchedProjectAccessTokenRequestScopesEnum {
    Bcfread = 'bcf:read',
    Bcfwrite = 'bcf:write',
    Documentread = 'document:read',
    Documentwrite = 'document:write',
    Ifcread = 'ifc:read',
    Ifcwrite = 'ifc:write',
    Modelread = 'model:read',
    Modelwrite = 'model:write'
}

export function PatchedProjectAccessTokenRequestFromJSON(json: any): PatchedProjectAccessTokenRequest {
    return PatchedProjectAccessTokenRequestFromJSONTyped(json, false);
}

export function PatchedProjectAccessTokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedProjectAccessTokenRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'scopes': !exists(json, 'scopes') ? undefined : json['scopes'],
        'expires_at': !exists(json, 'expires_at') ? undefined : (new Date(json['expires_at'])),
    };
}

export function PatchedProjectAccessTokenRequestToJSON(value?: PatchedProjectAccessTokenRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'scopes': value.scopes,
        'expires_at': value.expires_at === undefined ? undefined : (value.expires_at.toISOString()),
    };
}

