/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedTopicStatusRequest
 */
export interface PatchedTopicStatusRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchedTopicStatusRequest
     */
    topicStatus?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedTopicStatusRequest
     */
    color?: string | null;
    /**
     * This field is automatically provided by the route, you don't need to provide it in the body
     * @type {number}
     * @memberof PatchedTopicStatusRequest
     */
    project?: number;
}

export function PatchedTopicStatusRequestFromJSON(json: any): PatchedTopicStatusRequest {
    return PatchedTopicStatusRequestFromJSONTyped(json, false);
}

export function PatchedTopicStatusRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedTopicStatusRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'topicStatus': !exists(json, 'topic_status') ? undefined : json['topic_status'],
        'color': !exists(json, 'color') ? undefined : json['color'],
        'project': !exists(json, 'project') ? undefined : json['project'],
    };
}

export function PatchedTopicStatusRequestToJSON(value?: PatchedTopicStatusRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'topic_status': value.topicStatus,
        'color': value.color,
        'project': value.project,
    };
}


