/* tslint:disable */
/* eslint-disable */
/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PropertyDefinitionRequest,
    PropertyDefinitionRequestFromJSON,
    PropertyDefinitionRequestFromJSONTyped,
    PropertyDefinitionRequestToJSON,
} from './PropertyDefinitionRequest';

/**
 * Adds nested create feature
 * @export
 * @interface PatchedPropertyRequest
 */
export interface PatchedPropertyRequest {
    /**
     * 
     * @type {PropertyDefinitionRequest}
     * @memberof PatchedPropertyRequest
     */
    definition?: PropertyDefinitionRequest;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof PatchedPropertyRequest
     */
    value?: { [key: string]: any; } | null;
}

export function PatchedPropertyRequestFromJSON(json: any): PatchedPropertyRequest {
    return PatchedPropertyRequestFromJSONTyped(json, false);
}

export function PatchedPropertyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedPropertyRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'definition': !exists(json, 'definition') ? undefined : PropertyDefinitionRequestFromJSON(json['definition']),
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function PatchedPropertyRequestToJSON(value?: PatchedPropertyRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'definition': PropertyDefinitionRequestToJSON(value.definition),
        'value': value.value,
    };
}

