/* tslint:disable */
/* eslint-disable */
/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedStageRequest
 */
export interface PatchedStageRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchedStageRequest
     */
    stage?: string;
    /**
     * This field is automatically provided by the route, you don't need to provide it in the body
     * @type {number}
     * @memberof PatchedStageRequest
     */
    project?: number;
}

export function PatchedStageRequestFromJSON(json: any): PatchedStageRequest {
    return PatchedStageRequestFromJSONTyped(json, false);
}

export function PatchedStageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedStageRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'stage': !exists(json, 'stage') ? undefined : json['stage'],
        'project': !exists(json, 'project') ? undefined : json['project'],
    };
}

export function PatchedStageRequestToJSON(value?: PatchedStageRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'stage': value.stage,
        'project': value.project,
    };
}

