/* tslint:disable */
/* eslint-disable */
/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedEditFolderRequest
 */
export interface PatchedEditFolderRequest {
    /**
     * Permission for a Folder
     * 
     * * `1` - denied
     * * `50` - read_only
     * * `100` - read_write
     * @type {number}
     * @memberof PatchedEditFolderRequest
     */
    default_permission?: PatchedEditFolderRequestDefaultPermissionEnum;
    /**
     * 
     * @type {number}
     * @memberof PatchedEditFolderRequest
     */
    parent_id?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedEditFolderRequest
     */
    propagate?: boolean;
    /**
     * Name of the folder
     * @type {string}
     * @memberof PatchedEditFolderRequest
     */
    name?: string;
}

/**
* @export
* @enum {string}
*/
export enum PatchedEditFolderRequestDefaultPermissionEnum {
    NUMBER_1 = 1,
    NUMBER_50 = 50,
    NUMBER_100 = 100
}

export function PatchedEditFolderRequestFromJSON(json: any): PatchedEditFolderRequest {
    return PatchedEditFolderRequestFromJSONTyped(json, false);
}

export function PatchedEditFolderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedEditFolderRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'default_permission': !exists(json, 'default_permission') ? undefined : json['default_permission'],
        'parent_id': !exists(json, 'parent_id') ? undefined : json['parent_id'],
        'propagate': !exists(json, 'propagate') ? undefined : json['propagate'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function PatchedEditFolderRequestToJSON(value?: PatchedEditFolderRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'default_permission': value.default_permission,
        'parent_id': value.parent_id,
        'propagate': value.propagate,
        'name': value.name,
    };
}

