/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CloudRoleEnum,
    CloudRoleEnumFromJSON,
    CloudRoleEnumFromJSONTyped,
    CloudRoleEnumToJSON,
} from './CloudRoleEnum';

/**
 * 
 * @export
 * @interface PatchedUserCloudUpdateRequest
 */
export interface PatchedUserCloudUpdateRequest {
    /**
     * Role of the user in the cloud
     * @type {CloudRoleEnum}
     * @memberof PatchedUserCloudUpdateRequest
     */
    role?: CloudRoleEnum | null;
}

export function PatchedUserCloudUpdateRequestFromJSON(json: any): PatchedUserCloudUpdateRequest {
    return PatchedUserCloudUpdateRequestFromJSONTyped(json, false);
}

export function PatchedUserCloudUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedUserCloudUpdateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'role': !exists(json, 'role') ? undefined : CloudRoleEnumFromJSON(json['role']),
    };
}

export function PatchedUserCloudUpdateRequestToJSON(value?: PatchedUserCloudUpdateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'role': CloudRoleEnumToJSON(value.role),
    };
}

