/* tslint:disable */
/* eslint-disable */
/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedStoreyBuildingRequest
 */
export interface PatchedStoreyBuildingRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchedStoreyBuildingRequest
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedStoreyBuildingRequest
     */
    bimdata_elevation?: number;
}

export function PatchedStoreyBuildingRequestFromJSON(json: any): PatchedStoreyBuildingRequest {
    return PatchedStoreyBuildingRequestFromJSONTyped(json, false);
}

export function PatchedStoreyBuildingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedStoreyBuildingRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'bimdata_elevation': !exists(json, 'bimdata_elevation') ? undefined : json['bimdata_elevation'],
    };
}

export function PatchedStoreyBuildingRequestToJSON(value?: PatchedStoreyBuildingRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'bimdata_elevation': value.bimdata_elevation,
    };
}

