/* tslint:disable */
/* eslint-disable */
/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedVisaValidationRequest
 */
export interface PatchedVisaValidationRequest {
    /**
     * This is the userproject_id
     * @type {number}
     * @memberof PatchedVisaValidationRequest
     */
    validator_id?: number;
    /**
     * 
     * @type {Blob}
     * @memberof PatchedVisaValidationRequest
     */
    attachment?: Blob | null;
}

export function PatchedVisaValidationRequestFromJSON(json: any): PatchedVisaValidationRequest {
    return PatchedVisaValidationRequestFromJSONTyped(json, false);
}

export function PatchedVisaValidationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedVisaValidationRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'validator_id': !exists(json, 'validator_id') ? undefined : json['validator_id'],
        'attachment': !exists(json, 'attachment') ? undefined : json['attachment'],
    };
}

export function PatchedVisaValidationRequestToJSON(value?: PatchedVisaValidationRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'validator_id': value.validator_id,
        'attachment': value.attachment,
    };
}

