/* tslint:disable */
/* eslint-disable */
/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedIfcAccessTokenRequest
 */
export interface PatchedIfcAccessTokenRequest {
    /**
     * 
     * @type {boolean}
     * @memberof PatchedIfcAccessTokenRequest
     */
    read_only?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof PatchedIfcAccessTokenRequest
     */
    expires_at?: Date;
}

export function PatchedIfcAccessTokenRequestFromJSON(json: any): PatchedIfcAccessTokenRequest {
    return PatchedIfcAccessTokenRequestFromJSONTyped(json, false);
}

export function PatchedIfcAccessTokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedIfcAccessTokenRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'read_only': !exists(json, 'read_only') ? undefined : json['read_only'],
        'expires_at': !exists(json, 'expires_at') ? undefined : (new Date(json['expires_at'])),
    };
}

export function PatchedIfcAccessTokenRequestToJSON(value?: PatchedIfcAccessTokenRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'read_only': value.read_only,
        'expires_at': value.expires_at === undefined ? undefined : (value.expires_at.toISOString()),
    };
}

