/* tslint:disable */
/* eslint-disable */
/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedBcfProjectRequest
 */
export interface PatchedBcfProjectRequest {
    /**
     * Name of the project
     * @type {string}
     * @memberof PatchedBcfProjectRequest
     */
    name?: string;
}

export function PatchedBcfProjectRequestFromJSON(json: any): PatchedBcfProjectRequest {
    return PatchedBcfProjectRequestFromJSONTyped(json, false);
}

export function PatchedBcfProjectRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedBcfProjectRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function PatchedBcfProjectRequestToJSON(value?: PatchedBcfProjectRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

