/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AnyType,
    AnyTypeFromJSON,
    AnyTypeFromJSONTyped,
    AnyTypeToJSON,
    PropertyDefinitionRequest,
    PropertyDefinitionRequestFromJSON,
    PropertyDefinitionRequestFromJSONTyped,
    PropertyDefinitionRequestToJSON,
} from './';

/**
 * Adds nested create feature
 * @export
 * @interface PatchedPropertyRequest
 */
export interface PatchedPropertyRequest {
    /**
     * 
     * @type {PropertyDefinitionRequest}
     * @memberof PatchedPropertyRequest
     */
    definition?: PropertyDefinitionRequest;
    /**
     * 
     * @type {{ [key: string]: AnyType; }}
     * @memberof PatchedPropertyRequest
     */
    value?: { [key: string]: AnyType; } | null;
}

export function PatchedPropertyRequestFromJSON(json: any): PatchedPropertyRequest {
    return PatchedPropertyRequestFromJSONTyped(json, false);
}

export function PatchedPropertyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedPropertyRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'definition': !exists(json, 'definition') ? undefined : PropertyDefinitionRequestFromJSON(json['definition']),
        'value': !exists(json, 'value') ? undefined : (json['value'] === null ? null : mapValues(json['value'], AnyTypeFromJSON)),
    };
}

export function PatchedPropertyRequestToJSON(value?: PatchedPropertyRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'definition': PropertyDefinitionRequestToJSON(value.definition),
        'value': value.value === undefined ? undefined : (value.value === null ? null : mapValues(value.value, AnyTypeToJSON)),
    };
}


