/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    UnitRequest,
    UnitRequestFromJSON,
    UnitRequestFromJSONTyped,
    UnitRequestToJSON,
} from './';

/**
 * Adds nested create feature
 * @export
 * @interface PatchedPropertyDefinitionRequest
 */
export interface PatchedPropertyDefinitionRequest {
    /**
     * 
     * @type {UnitRequest}
     * @memberof PatchedPropertyDefinitionRequest
     */
    unit?: UnitRequest | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedPropertyDefinitionRequest
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedPropertyDefinitionRequest
     */
    description?: string | null;
    /**
     * IfcProperty*, Ifc*Properties, IfcComplexProperty, IfcQuantity*, IfcComplexQuantity, Attribute
     * @type {string}
     * @memberof PatchedPropertyDefinitionRequest
     */
    type?: string | null;
    /**
     * Type of the corresponding value (Boolean, integer, float, string, IfcRange, ...)
     * @type {string}
     * @memberof PatchedPropertyDefinitionRequest
     */
    valueType?: string | null;
}

export function PatchedPropertyDefinitionRequestFromJSON(json: any): PatchedPropertyDefinitionRequest {
    return PatchedPropertyDefinitionRequestFromJSONTyped(json, false);
}

export function PatchedPropertyDefinitionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedPropertyDefinitionRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'unit': !exists(json, 'unit') ? undefined : UnitRequestFromJSON(json['unit']),
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'valueType': !exists(json, 'value_type') ? undefined : json['value_type'],
    };
}

export function PatchedPropertyDefinitionRequestToJSON(value?: PatchedPropertyDefinitionRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'unit': UnitRequestToJSON(value.unit),
        'name': value.name,
        'description': value.description,
        'type': value.type,
        'value_type': value.valueType,
    };
}


