/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ProjectStatusEnum,
    ProjectStatusEnumFromJSON,
    ProjectStatusEnumFromJSONTyped,
    ProjectStatusEnumToJSON,
} from './ProjectStatusEnum';

/**
 * 
 * @export
 * @interface PatchedProjectRequest
 */
export interface PatchedProjectRequest {
    /**
     * 
     * @type {Blob}
     * @memberof PatchedProjectRequest
     */
    logo?: Blob | null;
    /**
     * Name of the project
     * @type {string}
     * @memberof PatchedProjectRequest
     */
    name?: string;
    /**
     * 
     * @type {ProjectStatusEnum}
     * @memberof PatchedProjectRequest
     */
    status?: ProjectStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof PatchedProjectRequest
     */
    parentId?: number | null;
}

export function PatchedProjectRequestFromJSON(json: any): PatchedProjectRequest {
    return PatchedProjectRequestFromJSONTyped(json, false);
}

export function PatchedProjectRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedProjectRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'logo': !exists(json, 'logo') ? undefined : json['logo'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'status': !exists(json, 'status') ? undefined : ProjectStatusEnumFromJSON(json['status']),
        'parentId': !exists(json, 'parent_id') ? undefined : json['parent_id'],
    };
}

export function PatchedProjectRequestToJSON(value?: PatchedProjectRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'logo': value.logo,
        'name': value.name,
        'status': ProjectStatusEnumToJSON(value.status),
        'parent_id': value.parentId,
    };
}

