/* tslint:disable */
/* eslint-disable */
/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedLabelRequest
 */
export interface PatchedLabelRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchedLabelRequest
     */
    label?: string;
}

export function PatchedLabelRequestFromJSON(json: any): PatchedLabelRequest {
    return PatchedLabelRequestFromJSONTyped(json, false);
}

export function PatchedLabelRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedLabelRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'label': !exists(json, 'label') ? undefined : json['label'],
    };
}

export function PatchedLabelRequestToJSON(value?: PatchedLabelRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'label': value.label,
    };
}

