/* tslint:disable */
/* eslint-disable */
/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CommentRequest,
    CommentRequestFromJSON,
    CommentRequestFromJSONTyped,
    CommentRequestToJSON,
} from './CommentRequest';
import {
    ViewpointRequest,
    ViewpointRequestFromJSON,
    ViewpointRequestFromJSONTyped,
    ViewpointRequestToJSON,
} from './ViewpointRequest';

/**
 * 
 * @export
 * @interface PatchedFullTopicRequest
 */
export interface PatchedFullTopicRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchedFullTopicRequest
     */
    guid?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedFullTopicRequest
     */
    creationDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof PatchedFullTopicRequest
     */
    creationAuthor?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedFullTopicRequest
     */
    modifiedAuthor?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedFullTopicRequest
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedFullTopicRequest
     */
    description?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof PatchedFullTopicRequest
     */
    referenceLinks?: Array<string> | null;
    /**
     * DEPRECATED: Use 'models' instead
     * @type {Array<number>}
     * @memberof PatchedFullTopicRequest
     */
    ifcs?: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof PatchedFullTopicRequest
     */
    models?: Array<number>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PatchedFullTopicRequest
     */
    labels?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof PatchedFullTopicRequest
     */
    topicType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedFullTopicRequest
     */
    topicStatus?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedFullTopicRequest
     */
    stage?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedFullTopicRequest
     */
    priority?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedFullTopicRequest
     */
    index?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedFullTopicRequest
     */
    assignedTo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedFullTopicRequest
     */
    format?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedFullTopicRequest
     */
    dueDate?: Date | null;
    /**
     * 
     * @type {Array<CommentRequest>}
     * @memberof PatchedFullTopicRequest
     */
    comments?: Array<CommentRequest>;
    /**
     * 
     * @type {Array<ViewpointRequest>}
     * @memberof PatchedFullTopicRequest
     */
    viewpoints?: Array<ViewpointRequest>;
    /**
     * 
     * @type {number}
     * @memberof PatchedFullTopicRequest
     */
    project?: number;
}

export function PatchedFullTopicRequestFromJSON(json: any): PatchedFullTopicRequest {
    return PatchedFullTopicRequestFromJSONTyped(json, false);
}

export function PatchedFullTopicRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedFullTopicRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'guid': !exists(json, 'guid') ? undefined : json['guid'],
        'creationDate': !exists(json, 'creation_date') ? undefined : (new Date(json['creation_date'])),
        'creationAuthor': !exists(json, 'creation_author') ? undefined : json['creation_author'],
        'modifiedAuthor': !exists(json, 'modified_author') ? undefined : json['modified_author'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'referenceLinks': !exists(json, 'reference_links') ? undefined : json['reference_links'],
        'ifcs': !exists(json, 'ifcs') ? undefined : json['ifcs'],
        'models': !exists(json, 'models') ? undefined : json['models'],
        'labels': !exists(json, 'labels') ? undefined : json['labels'],
        'topicType': !exists(json, 'topic_type') ? undefined : json['topic_type'],
        'topicStatus': !exists(json, 'topic_status') ? undefined : json['topic_status'],
        'stage': !exists(json, 'stage') ? undefined : json['stage'],
        'priority': !exists(json, 'priority') ? undefined : json['priority'],
        'index': !exists(json, 'index') ? undefined : json['index'],
        'assignedTo': !exists(json, 'assigned_to') ? undefined : json['assigned_to'],
        'format': !exists(json, 'format') ? undefined : json['format'],
        'dueDate': !exists(json, 'due_date') ? undefined : (json['due_date'] === null ? null : new Date(json['due_date'])),
        'comments': !exists(json, 'comments') ? undefined : ((json['comments'] as Array<any>).map(CommentRequestFromJSON)),
        'viewpoints': !exists(json, 'viewpoints') ? undefined : ((json['viewpoints'] as Array<any>).map(ViewpointRequestFromJSON)),
        'project': !exists(json, 'project') ? undefined : json['project'],
    };
}

export function PatchedFullTopicRequestToJSON(value?: PatchedFullTopicRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'guid': value.guid,
        'creation_date': value.creationDate === undefined ? undefined : (value.creationDate.toISOString()),
        'creation_author': value.creationAuthor,
        'modified_author': value.modifiedAuthor,
        'title': value.title,
        'description': value.description,
        'reference_links': value.referenceLinks,
        'ifcs': value.ifcs,
        'models': value.models,
        'labels': value.labels,
        'topic_type': value.topicType,
        'topic_status': value.topicStatus,
        'stage': value.stage,
        'priority': value.priority,
        'index': value.index,
        'assigned_to': value.assignedTo,
        'format': value.format,
        'due_date': value.dueDate === undefined ? undefined : (value.dueDate === null ? null : value.dueDate.toISOString()),
        'comments': value.comments === undefined ? undefined : ((value.comments as Array<any>).map(CommentRequestToJSON)),
        'viewpoints': value.viewpoints === undefined ? undefined : ((value.viewpoints as Array<any>).map(ViewpointRequestToJSON)),
        'project': value.project,
    };
}

