/* tslint:disable */
/* eslint-disable */
/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedModelEquipmentRequest
 */
export interface PatchedModelEquipmentRequest {
    /**
     * Name of the equipment
     * @type {string}
     * @memberof PatchedModelEquipmentRequest
     */
    name?: string;
    /**
     * Description of the equipment
     * @type {string}
     * @memberof PatchedModelEquipmentRequest
     */
    description?: string | null;
    /**
     * An optional link to the equipment reference.
     * @type {string}
     * @memberof PatchedModelEquipmentRequest
     */
    reference_link?: string | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof PatchedModelEquipmentRequest
     */
    position?: Array<number>;
}

export function PatchedModelEquipmentRequestFromJSON(json: any): PatchedModelEquipmentRequest {
    return PatchedModelEquipmentRequestFromJSONTyped(json, false);
}

export function PatchedModelEquipmentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedModelEquipmentRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'reference_link': !exists(json, 'reference_link') ? undefined : json['reference_link'],
        'position': !exists(json, 'position') ? undefined : json['position'],
    };
}

export function PatchedModelEquipmentRequestToJSON(value?: PatchedModelEquipmentRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'reference_link': value.reference_link,
        'position': value.position,
    };
}

