/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedWebHookRequest
 */
export interface PatchedWebHookRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof PatchedWebHookRequest
     */
    events?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof PatchedWebHookRequest
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedWebHookRequest
     */
    secret?: string;
}

export function PatchedWebHookRequestFromJSON(json: any): PatchedWebHookRequest {
    return PatchedWebHookRequestFromJSONTyped(json, false);
}

export function PatchedWebHookRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedWebHookRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'events': !exists(json, 'events') ? undefined : json['events'],
        'url': !exists(json, 'url') ? undefined : json['url'],
        'secret': !exists(json, 'secret') ? undefined : json['secret'],
    };
}

export function PatchedWebHookRequestToJSON(value?: PatchedWebHookRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'events': value.events,
        'url': value.url,
        'secret': value.secret,
    };
}

