/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Direction,
    DirectionFromJSON,
    DirectionFromJSONTyped,
    DirectionToJSON,
} from './Direction';
import {
    Point,
    PointFromJSON,
    PointFromJSONTyped,
    PointToJSON,
} from './Point';

/**
 * Adds nested create feature
 * @export
 * @interface PerspectiveCamera
 */
export interface PerspectiveCamera {
    /**
     * 
     * @type {number}
     * @memberof PerspectiveCamera
     */
    fieldOfView: number;
    /**
     * 
     * @type {Direction}
     * @memberof PerspectiveCamera
     */
    cameraDirection: Direction;
    /**
     * 
     * @type {Direction}
     * @memberof PerspectiveCamera
     */
    cameraUpVector: Direction;
    /**
     * 
     * @type {Point}
     * @memberof PerspectiveCamera
     */
    cameraViewPoint: Point;
    /**
     * 
     * @type {Direction}
     * @memberof PerspectiveCamera
     */
    bimdataCameraDirection?: Direction;
}

export function PerspectiveCameraFromJSON(json: any): PerspectiveCamera {
    return PerspectiveCameraFromJSONTyped(json, false);
}

export function PerspectiveCameraFromJSONTyped(json: any, ignoreDiscriminator: boolean): PerspectiveCamera {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fieldOfView': json['field_of_view'],
        'cameraDirection': DirectionFromJSON(json['camera_direction']),
        'cameraUpVector': DirectionFromJSON(json['camera_up_vector']),
        'cameraViewPoint': PointFromJSON(json['camera_view_point']),
        'bimdataCameraDirection': !exists(json, 'bimdata_camera_direction') ? undefined : DirectionFromJSON(json['bimdata_camera_direction']),
    };
}

export function PerspectiveCameraToJSON(value?: PerspectiveCamera | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'field_of_view': value.fieldOfView,
        'camera_direction': DirectionToJSON(value.cameraDirection),
        'camera_up_vector': DirectionToJSON(value.cameraUpVector),
        'camera_view_point': PointToJSON(value.cameraViewPoint),
        'bimdata_camera_direction': DirectionToJSON(value.bimdataCameraDirection),
    };
}

