/* tslint:disable */
/* eslint-disable */
/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Point,
    PointFromJSON,
    PointFromJSONTyped,
    PointToJSON,
} from './Point';

/**
 * Adds nested create feature
 * @export
 * @interface Pin
 */
export interface Pin {
    /**
     * 
     * @type {number}
     * @memberof Pin
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof Pin
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Pin
     */
    color?: string | null;
    /**
     * 
     * @type {Point}
     * @memberof Pin
     */
    point: Point;
}

export function PinFromJSON(json: any): Pin {
    return PinFromJSONTyped(json, false);
}

export function PinFromJSONTyped(json: any, ignoreDiscriminator: boolean): Pin {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'color': !exists(json, 'color') ? undefined : json['color'],
        'point': PointFromJSON(json['point']),
    };
}

export function PinToJSON(value?: Pin | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'color': value.color,
        'point': PointToJSON(value.point),
    };
}

