/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ModelStatusEnum,
    ModelStatusEnumFromJSON,
    ModelStatusEnumFromJSONTyped,
    ModelStatusEnumToJSON,
} from './ModelStatusEnum';

/**
 * 
 * @export
 * @interface ProcessorHandler
 */
export interface ProcessorHandler {
    /**
     * 
     * @type {number}
     * @memberof ProcessorHandler
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof ProcessorHandler
     */
    readonly worker: string;
    /**
     * 
     * @type {ModelStatusEnum}
     * @memberof ProcessorHandler
     */
    status?: ModelStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ProcessorHandler
     */
    detailMessage?: string | null;
}

export function ProcessorHandlerFromJSON(json: any): ProcessorHandler {
    return ProcessorHandlerFromJSONTyped(json, false);
}

export function ProcessorHandlerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcessorHandler {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'worker': json['worker'],
        'status': !exists(json, 'status') ? undefined : ModelStatusEnumFromJSON(json['status']),
        'detailMessage': !exists(json, 'detail_message') ? undefined : json['detail_message'],
    };
}

export function ProcessorHandlerToJSON(value?: ProcessorHandler | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': ModelStatusEnumToJSON(value.status),
        'detail_message': value.detailMessage,
    };
}

