/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ProjectStatusEnum {
    A = 'A',
    D = 'D'
}

export function ProjectStatusEnumFromJSON(json: any): ProjectStatusEnum {
    return ProjectStatusEnumFromJSONTyped(json, false);
}

export function ProjectStatusEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectStatusEnum {
    return json as ProjectStatusEnum;
}

export function ProjectStatusEnumToJSON(value?: ProjectStatusEnum | null): any {
    return value as any;
}

