/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectAccessToken
 */
export interface ProjectAccessToken {
    /**
     * 
     * @type {string}
     * @memberof ProjectAccessToken
     */
    readonly token: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProjectAccessToken
     */
    scopes: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof ProjectAccessToken
     */
    expiresAt?: Date;
}

export function ProjectAccessTokenFromJSON(json: any): ProjectAccessToken {
    return ProjectAccessTokenFromJSONTyped(json, false);
}

export function ProjectAccessTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectAccessToken {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': json['token'],
        'scopes': json['scopes'],
        'expiresAt': !exists(json, 'expires_at') ? undefined : (new Date(json['expires_at'])),
    };
}

export function ProjectAccessTokenToJSON(value?: ProjectAccessToken | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'scopes': value.scopes,
        'expires_at': value.expiresAt === undefined ? undefined : (value.expiresAt.toISOString()),
    };
}


