/* tslint:disable */
/* eslint-disable */
/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    FolderTree,
    FolderTreeFromJSON,
    FolderTreeFromJSONTyped,
    FolderTreeToJSON,
} from './FolderTree';

/**
 * 
 * @export
 * @interface ProjectFolderTree
 */
export interface ProjectFolderTree {
    /**
     * 
     * @type {string}
     * @memberof ProjectFolderTree
     */
    name: string;
    /**
     * 
     * @type {Array<FolderTree>}
     * @memberof ProjectFolderTree
     */
    folders: Array<FolderTree>;
}

export function ProjectFolderTreeFromJSON(json: any): ProjectFolderTree {
    return ProjectFolderTreeFromJSONTyped(json, false);
}

export function ProjectFolderTreeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectFolderTree {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'folders': ((json['folders'] as Array<any>).map(FolderTreeFromJSON)),
    };
}

export function ProjectFolderTreeToJSON(value?: ProjectFolderTree | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'folders': ((value.folders as Array<any>).map(FolderTreeToJSON)),
    };
}

