/* tslint:disable */
/* eslint-disable */
/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectAccessTokenRequest
 */
export interface ProjectAccessTokenRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof ProjectAccessTokenRequest
     */
    scopes: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof ProjectAccessTokenRequest
     */
    expiresAt?: Date;
}

export function ProjectAccessTokenRequestFromJSON(json: any): ProjectAccessTokenRequest {
    return ProjectAccessTokenRequestFromJSONTyped(json, false);
}

export function ProjectAccessTokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectAccessTokenRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'scopes': json['scopes'],
        'expiresAt': !exists(json, 'expires_at') ? undefined : (new Date(json['expires_at'])),
    };
}

export function ProjectAccessTokenRequestToJSON(value?: ProjectAccessTokenRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'scopes': value.scopes,
        'expires_at': value.expiresAt === undefined ? undefined : (value.expiresAt.toISOString()),
    };
}

