/* tslint:disable */
/* eslint-disable */
/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PropertyDefinition,
    PropertyDefinitionFromJSON,
    PropertyDefinitionFromJSONTyped,
    PropertyDefinitionToJSON,
} from './';

/**
 * 
 * @export
 * @interface Property
 */
export interface Property {
    /**
     * 
     * @type {number}
     * @memberof Property
     */
    readonly id?: number;
    /**
     * 
     * @type {PropertyDefinition}
     * @memberof Property
     */
    definition: PropertyDefinition;
    /**
     * 
     * @type {object}
     * @memberof Property
     */
    value?: object | null;
    /**
     * This field is useful when you update a property and the  API is rebuilding a new property set to avoid an update on many elements. It gives you the new pset id
     * @type {string}
     * @memberof Property
     */
    readonly propertySetId?: string;
    /**
     * 
     * @type {Date}
     * @memberof Property
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Property
     */
    readonly updatedAt?: Date;
}

export function PropertyFromJSON(json: any): Property {
    return PropertyFromJSONTyped(json, false);
}

export function PropertyFromJSONTyped(json: any, ignoreDiscriminator: boolean): Property {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'definition': PropertyDefinitionFromJSON(json['definition']),
        'value': !exists(json, 'value') ? undefined : json['value'],
        'propertySetId': !exists(json, 'property_set_id') ? undefined : json['property_set_id'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'updatedAt': !exists(json, 'updated_at') ? undefined : (new Date(json['updated_at'])),
    };
}

export function PropertyToJSON(value?: Property | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'definition': PropertyDefinitionToJSON(value.definition),
        'value': value.value,
    };
}


