/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    RawMaterial,
    RawMaterialFromJSON,
    RawMaterialFromJSONTyped,
    RawMaterialToJSON,
} from './RawMaterial';
import {
    RawMaterialListComponents,
    RawMaterialListComponentsFromJSON,
    RawMaterialListComponentsFromJSONTyped,
    RawMaterialListComponentsToJSON,
} from './RawMaterialListComponents';
import {
    RawMaterialOptions,
    RawMaterialOptionsFromJSON,
    RawMaterialOptionsFromJSONTyped,
    RawMaterialOptionsToJSON,
} from './RawMaterialOptions';

/**
 * 
 * @export
 * @interface RawMaterialList
 */
export interface RawMaterialList {
    /**
     * 
     * @type {Array<RawMaterial>}
     * @memberof RawMaterialList
     */
    materialsData?: Array<RawMaterial> | null;
    /**
     * 
     * @type {Array<RawMaterialListComponents>}
     * @memberof RawMaterialList
     */
    listComponents?: Array<RawMaterialListComponents> | null;
    /**
     * 
     * @type {Array<RawMaterialOptions>}
     * @memberof RawMaterialList
     */
    options?: Array<RawMaterialOptions> | null;
}

export function RawMaterialListFromJSON(json: any): RawMaterialList {
    return RawMaterialListFromJSONTyped(json, false);
}

export function RawMaterialListFromJSONTyped(json: any, ignoreDiscriminator: boolean): RawMaterialList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'materialsData': !exists(json, 'materials_data') ? undefined : (json['materials_data'] === null ? null : (json['materials_data'] as Array<any>).map(RawMaterialFromJSON)),
        'listComponents': !exists(json, 'list_components') ? undefined : (json['list_components'] === null ? null : (json['list_components'] as Array<any>).map(RawMaterialListComponentsFromJSON)),
        'options': !exists(json, 'options') ? undefined : (json['options'] === null ? null : (json['options'] as Array<any>).map(RawMaterialOptionsFromJSON)),
    };
}

export function RawMaterialListToJSON(value?: RawMaterialList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'materials_data': value.materialsData === undefined ? undefined : (value.materialsData === null ? null : (value.materialsData as Array<any>).map(RawMaterialToJSON)),
        'list_components': value.listComponents === undefined ? undefined : (value.listComponents === null ? null : (value.listComponents as Array<any>).map(RawMaterialListComponentsToJSON)),
        'options': value.options === undefined ? undefined : (value.options === null ? null : (value.options as Array<any>).map(RawMaterialOptionsToJSON)),
    };
}

