/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RawPropertyRequest
 */
export interface RawPropertyRequest {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof RawPropertyRequest
     */
    value?: { [key: string]: any; } | null;
    /**
     * 
     * @type {number}
     * @memberof RawPropertyRequest
     */
    defId: number;
}

export function RawPropertyRequestFromJSON(json: any): RawPropertyRequest {
    return RawPropertyRequestFromJSONTyped(json, false);
}

export function RawPropertyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RawPropertyRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': !exists(json, 'value') ? undefined : json['value'],
        'defId': json['def_id'],
    };
}

export function RawPropertyRequestToJSON(value?: RawPropertyRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': value.value,
        'def_id': value.defId,
    };
}

