/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum RecursiveFolderChildrenTypeEnum {
    Folder = 'Folder',
    Document = 'Document',
    Ifc = 'Ifc'
}

export function RecursiveFolderChildrenTypeEnumFromJSON(json: any): RecursiveFolderChildrenTypeEnum {
    return RecursiveFolderChildrenTypeEnumFromJSONTyped(json, false);
}

export function RecursiveFolderChildrenTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecursiveFolderChildrenTypeEnum {
    return json as RecursiveFolderChildrenTypeEnum;
}

export function RecursiveFolderChildrenTypeEnumToJSON(value?: RecursiveFolderChildrenTypeEnum | null): any {
    return value as any;
}

