/* tslint:disable */
/* eslint-disable */
/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Component,
    ComponentFromJSON,
    ComponentFromJSONTyped,
    ComponentToJSON,
} from './Component';

/**
 * 
 * @export
 * @interface SelectionDefinition
 */
export interface SelectionDefinition {
    /**
     * 
     * @type {Array<Component>}
     * @memberof SelectionDefinition
     */
    selection: Array<Component>;
}

export function SelectionDefinitionFromJSON(json: any): SelectionDefinition {
    return SelectionDefinitionFromJSONTyped(json, false);
}

export function SelectionDefinitionFromJSONTyped(json: any, ignoreDiscriminator: boolean): SelectionDefinition {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'selection': ((json['selection'] as Array<any>).map(ComponentFromJSON)),
    };
}

export function SelectionDefinitionToJSON(value?: SelectionDefinition | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'selection': ((value.selection as Array<any>).map(ComponentToJSON)),
    };
}

