/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StageRequest
 */
export interface StageRequest {
    /**
     * 
     * @type {string}
     * @memberof StageRequest
     */
    stage: string;
    /**
     * This field is automatically provided by the route, you don't need to provide it in the body
     * @type {number}
     * @memberof StageRequest
     */
    project?: number;
}

export function StageRequestFromJSON(json: any): StageRequest {
    return StageRequestFromJSONTyped(json, false);
}

export function StageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StageRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'stage': json['stage'],
        'project': !exists(json, 'project') ? undefined : json['project'],
    };
}

export function StageRequestToJSON(value?: StageRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'stage': value.stage,
        'project': value.project,
    };
}


