/* tslint:disable */
/* eslint-disable */
/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ModelWithPositioningPlan,
    ModelWithPositioningPlanFromJSON,
    ModelWithPositioningPlanFromJSONTyped,
    ModelWithPositioningPlanToJSON,
} from './';

/**
 * 
 * @export
 * @interface Storey
 */
export interface Storey {
    /**
     * 
     * @type {number}
     * @memberof Storey
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof Storey
     */
    readonly ifcId?: string;
    /**
     * 
     * @type {string}
     * @memberof Storey
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof Storey
     */
    elevation?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Storey
     */
    readonly order?: number;
    /**
     * 
     * @type {Array<ModelWithPositioningPlan>}
     * @memberof Storey
     */
    readonly models?: Array<ModelWithPositioningPlan>;
    /**
     * 
     * @type {number}
     * @memberof Storey
     */
    readonly modelsUnreachableCount?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Storey
     */
    readonly isSite?: boolean;
}

export function StoreyFromJSON(json: any): Storey {
    return StoreyFromJSONTyped(json, false);
}

export function StoreyFromJSONTyped(json: any, ignoreDiscriminator: boolean): Storey {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'ifcId': !exists(json, 'ifc_id') ? undefined : json['ifc_id'],
        'name': json['name'],
        'elevation': !exists(json, 'elevation') ? undefined : json['elevation'],
        'order': !exists(json, 'order') ? undefined : json['order'],
        'models': !exists(json, 'models') ? undefined : ((json['models'] as Array<any>).map(ModelWithPositioningPlanFromJSON)),
        'modelsUnreachableCount': !exists(json, 'models_unreachable_count') ? undefined : json['models_unreachable_count'],
        'isSite': !exists(json, 'is_site') ? undefined : json['is_site'],
    };
}

export function StoreyToJSON(value?: Storey | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'elevation': value.elevation,
    };
}


