/* tslint:disable */
/* eslint-disable */
/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TopicTypeRequest
 */
export interface TopicTypeRequest {
    /**
     * 
     * @type {string}
     * @memberof TopicTypeRequest
     */
    topic_type: string;
}

export function TopicTypeRequestFromJSON(json: any): TopicTypeRequest {
    return TopicTypeRequestFromJSONTyped(json, false);
}

export function TopicTypeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TopicTypeRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'topic_type': json['topic_type'],
    };
}

export function TopicTypeRequestToJSON(value?: TopicTypeRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'topic_type': value.topic_type,
    };
}

