/* tslint:disable */
/* eslint-disable */
/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Topic
 */
export interface Topic {
    /**
     * 
     * @type {string}
     * @memberof Topic
     */
    guid?: string;
    /**
     * 
     * @type {string}
     * @memberof Topic
     */
    topicType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Topic
     */
    topicStatus?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Topic
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Topic
     */
    priority?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof Topic
     */
    labels?: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof Topic
     */
    creationDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof Topic
     */
    creationAuthor?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Topic
     */
    readonly modifiedDate: Date;
    /**
     * 
     * @type {string}
     * @memberof Topic
     */
    modifiedAuthor?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Topic
     */
    assignedTo?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof Topic
     */
    referenceLinks?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof Topic
     */
    stage?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Topic
     */
    description?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Topic
     */
    dueDate?: Date | null;
    /**
     * DEPRECATED: Use 'models' instead
     * @type {Array<number>}
     * @memberof Topic
     */
    ifcs?: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof Topic
     */
    models?: Array<number>;
    /**
     * 
     * @type {string}
     * @memberof Topic
     */
    format?: string;
    /**
     * 
     * @type {number}
     * @memberof Topic
     */
    index?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Topic
     */
    project: number;
}

export function TopicFromJSON(json: any): Topic {
    return TopicFromJSONTyped(json, false);
}

export function TopicFromJSONTyped(json: any, ignoreDiscriminator: boolean): Topic {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'guid': !exists(json, 'guid') ? undefined : json['guid'],
        'topicType': !exists(json, 'topic_type') ? undefined : json['topic_type'],
        'topicStatus': !exists(json, 'topic_status') ? undefined : json['topic_status'],
        'title': json['title'],
        'priority': !exists(json, 'priority') ? undefined : json['priority'],
        'labels': !exists(json, 'labels') ? undefined : json['labels'],
        'creationDate': !exists(json, 'creation_date') ? undefined : (new Date(json['creation_date'])),
        'creationAuthor': !exists(json, 'creation_author') ? undefined : json['creation_author'],
        'modifiedDate': (new Date(json['modified_date'])),
        'modifiedAuthor': !exists(json, 'modified_author') ? undefined : json['modified_author'],
        'assignedTo': !exists(json, 'assigned_to') ? undefined : json['assigned_to'],
        'referenceLinks': !exists(json, 'reference_links') ? undefined : json['reference_links'],
        'stage': !exists(json, 'stage') ? undefined : json['stage'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'dueDate': !exists(json, 'due_date') ? undefined : (json['due_date'] === null ? null : new Date(json['due_date'])),
        'ifcs': !exists(json, 'ifcs') ? undefined : json['ifcs'],
        'models': !exists(json, 'models') ? undefined : json['models'],
        'format': !exists(json, 'format') ? undefined : json['format'],
        'index': !exists(json, 'index') ? undefined : json['index'],
        'project': json['project'],
    };
}

export function TopicToJSON(value?: Topic | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'guid': value.guid,
        'topic_type': value.topicType,
        'topic_status': value.topicStatus,
        'title': value.title,
        'priority': value.priority,
        'labels': value.labels,
        'creation_date': value.creationDate === undefined ? undefined : (value.creationDate.toISOString()),
        'creation_author': value.creationAuthor,
        'modified_author': value.modifiedAuthor,
        'assigned_to': value.assignedTo,
        'reference_links': value.referenceLinks,
        'stage': value.stage,
        'description': value.description,
        'due_date': value.dueDate === undefined ? undefined : (value.dueDate === null ? null : value.dueDate.toISOString()),
        'ifcs': value.ifcs,
        'models': value.models,
        'format': value.format,
        'index': value.index,
        'project': value.project,
    };
}

