/* tslint:disable */
/* eslint-disable */
/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Adds nested create feature
 * @export
 * @interface UnitRequest
 */
export interface UnitRequest {
    /**
     * IfcDerivedUnit, IfcContextDependentUnit, IfcConversionBasedUnit, IfcSIUnit or IfcMonetaryUnit
     * @type {string}
     * @memberof UnitRequest
     */
    type: string;
    /**
     * Name of the unit (ex: DEGREE)
     * @type {string}
     * @memberof UnitRequest
     */
    name?: string | null;
    /**
     * IFC type of the unit or user defined type (ex: PLANEANGLEUNIT for DEGREE and RADIAN)
     * @type {string}
     * @memberof UnitRequest
     */
    unitType?: string | null;
    /**
     * Litteral prefix for scale (ex: MILLI, KILO, etc..)
     * @type {string}
     * @memberof UnitRequest
     */
    prefix?: string | null;
    /**
     * List of 7 units dimensions
     * @type {Array<number>}
     * @memberof UnitRequest
     */
    dimensions?: Array<number> | null;
    /**
     * Factor of conversion and base unit id (ex: DEGREE from RADIAN with factor 0.0174532925199433)
     * @type {number}
     * @memberof UnitRequest
     */
    conversionFactor?: number | null;
    /**
     * 
     * @type {UnitRequest}
     * @memberof UnitRequest
     */
    conversionBaseunit?: UnitRequest;
    /**
     * List of constitutive unit elements by id with corresponding exponent (ex: [meterID/1, secondID/-1] for velocity)
     * @type {{ [key: string]: any; }}
     * @memberof UnitRequest
     */
    elements?: { [key: string]: any; } | null;
    /**
     * 
     * @type {boolean}
     * @memberof UnitRequest
     */
    isDefault?: boolean;
}

export function UnitRequestFromJSON(json: any): UnitRequest {
    return UnitRequestFromJSONTyped(json, false);
}

export function UnitRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnitRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'unitType': !exists(json, 'unit_type') ? undefined : json['unit_type'],
        'prefix': !exists(json, 'prefix') ? undefined : json['prefix'],
        'dimensions': !exists(json, 'dimensions') ? undefined : json['dimensions'],
        'conversionFactor': !exists(json, 'conversion_factor') ? undefined : json['conversion_factor'],
        'conversionBaseunit': !exists(json, 'conversion_baseunit') ? undefined : UnitRequestFromJSON(json['conversion_baseunit']),
        'elements': !exists(json, 'elements') ? undefined : json['elements'],
        'isDefault': !exists(json, 'is_default') ? undefined : json['is_default'],
    };
}

export function UnitRequestToJSON(value?: UnitRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'name': value.name,
        'unit_type': value.unitType,
        'prefix': value.prefix,
        'dimensions': value.dimensions,
        'conversion_factor': value.conversionFactor,
        'conversion_baseunit': UnitRequestToJSON(value.conversionBaseunit),
        'elements': value.elements,
        'is_default': value.isDefault,
    };
}

