/* tslint:disable */
/* eslint-disable */
/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserProjectUpdate
 */
export interface UserProjectUpdate {
    /**
     * User\'s role in the project
     * @type {number}
     * @memberof UserProjectUpdate
     */
    role?: number;
}

export function UserProjectUpdateFromJSON(json: any): UserProjectUpdate {
    return UserProjectUpdateFromJSONTyped(json, false);
}

export function UserProjectUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProjectUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'role': !exists(json, 'role') ? undefined : json['role'],
    };
}

export function UserProjectUpdateToJSON(value?: UserProjectUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'role': value.role,
    };
}


