/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserProjectIdRequest
 */
export interface UserProjectIdRequest {
    /**
     * 
     * @type {number}
     * @memberof UserProjectIdRequest
     */
    userprojectId: number;
}

export function UserProjectIdRequestFromJSON(json: any): UserProjectIdRequest {
    return UserProjectIdRequestFromJSONTyped(json, false);
}

export function UserProjectIdRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProjectIdRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userprojectId': json['userproject_id'],
    };
}

export function UserProjectIdRequestToJSON(value?: UserProjectIdRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userproject_id': value.userprojectId,
    };
}


