/* tslint:disable */
/* eslint-disable */
/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VisaRequest
 */
export interface VisaRequest {
    /**
     * This is the userproject_id. This field is only used if the call is made from an App
     * @type {number}
     * @memberof VisaRequest
     */
    creator_id?: number;
    /**
     * Description of the visa
     * @type {string}
     * @memberof VisaRequest
     */
    description?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof VisaRequest
     */
    deadline?: Date | null;
}

export function VisaRequestFromJSON(json: any): VisaRequest {
    return VisaRequestFromJSONTyped(json, false);
}

export function VisaRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VisaRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'creator_id': !exists(json, 'creator_id') ? undefined : json['creator_id'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'deadline': !exists(json, 'deadline') ? undefined : (json['deadline'] === null ? null : new Date(json['deadline'])),
    };
}

export function VisaRequestToJSON(value?: VisaRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'creator_id': value.creator_id,
        'description': value.description,
        'deadline': value.deadline === undefined ? undefined : (value.deadline === null ? null : value.deadline.toISOString().substr(0,10)),
    };
}

