/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum VisaStatusEnum {
    O = 'O',
    A = 'A',
    C = 'C'
}

export function VisaStatusEnumFromJSON(json: any): VisaStatusEnum {
    return VisaStatusEnumFromJSONTyped(json, false);
}

export function VisaStatusEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): VisaStatusEnum {
    return json as VisaStatusEnum;
}

export function VisaStatusEnumToJSON(value?: VisaStatusEnum | null): any {
    return value as any;
}

