/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    UserProject,
    UserProjectFromJSON,
    UserProjectFromJSONTyped,
    UserProjectToJSON,
    VisaValidationStatusEnum,
    VisaValidationStatusEnumFromJSON,
    VisaValidationStatusEnumFromJSONTyped,
    VisaValidationStatusEnumToJSON,
} from './';

/**
 * 
 * @export
 * @interface VisaValidation
 */
export interface VisaValidation {
    /**
     * 
     * @type {number}
     * @memberof VisaValidation
     */
    readonly id: number;
    /**
     * 
     * @type {number}
     * @memberof VisaValidation
     */
    readonly visaId: number;
    /**
     * 
     * @type {UserProject}
     * @memberof VisaValidation
     */
    readonly validator: UserProject;
    /**
     * 
     * @type {VisaValidationStatusEnum}
     * @memberof VisaValidation
     */
    readonly status: VisaValidationStatusEnum;
    /**
     * Return True if validator has commented the visa
     * @type {boolean}
     * @memberof VisaValidation
     */
    readonly hasCommented: boolean;
    /**
     * 
     * @type {Date}
     * @memberof VisaValidation
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof VisaValidation
     */
    readonly updatedAt: Date;
}

export function VisaValidationFromJSON(json: any): VisaValidation {
    return VisaValidationFromJSONTyped(json, false);
}

export function VisaValidationFromJSONTyped(json: any, ignoreDiscriminator: boolean): VisaValidation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'visaId': json['visa_id'],
        'validator': UserProjectFromJSON(json['validator']),
        'status': VisaValidationStatusEnumFromJSON(json['status']),
        'hasCommented': json['has_commented'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function VisaValidationToJSON(value?: VisaValidation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}


