/* tslint:disable */
/* eslint-disable */
/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    UserProject,
    UserProjectFromJSON,
    UserProjectFromJSONTyped,
    UserProjectToJSON,
} from './UserProject';

/**
 * 
 * @export
 * @interface VisaValidation
 */
export interface VisaValidation {
    /**
     * 
     * @type {number}
     * @memberof VisaValidation
     */
    readonly id: number;
    /**
     * 
     * @type {number}
     * @memberof VisaValidation
     */
    readonly visa_id: number;
    /**
     * 
     * @type {UserProject}
     * @memberof VisaValidation
     */
    readonly validator: UserProject | null;
    /**
     * 
     * @type {string}
     * @memberof VisaValidation
     */
    readonly status: VisaValidationStatusEnum;
    /**
     * Return True if validator has commented the visa
     * @type {boolean}
     * @memberof VisaValidation
     */
    readonly has_commented: boolean;
    /**
     * 
     * @type {Date}
     * @memberof VisaValidation
     */
    readonly created_at: Date;
    /**
     * 
     * @type {Date}
     * @memberof VisaValidation
     */
    readonly updated_at: Date;
}

/**
* @export
* @enum {string}
*/
export enum VisaValidationStatusEnum {
    P = 'P',
    A = 'A',
    D = 'D'
}

export function VisaValidationFromJSON(json: any): VisaValidation {
    return VisaValidationFromJSONTyped(json, false);
}

export function VisaValidationFromJSONTyped(json: any, ignoreDiscriminator: boolean): VisaValidation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'visa_id': json['visa_id'],
        'validator': UserProjectFromJSON(json['validator']),
        'status': json['status'],
        'has_commented': json['has_commented'],
        'created_at': (new Date(json['created_at'])),
        'updated_at': (new Date(json['updated_at'])),
    };
}

export function VisaValidationToJSON(value?: VisaValidation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

