/* tslint:disable */
/* eslint-disable */
/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebHook
 */
export interface WebHook {
    /**
     * 
     * @type {number}
     * @memberof WebHook
     */
    readonly id?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof WebHook
     */
    events: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof WebHook
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof WebHook
     */
    secret: string;
}

export function WebHookFromJSON(json: any): WebHook {
    return WebHookFromJSONTyped(json, false);
}

export function WebHookFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebHook {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'events': json['events'],
        'url': json['url'],
        'secret': json['secret'],
    };
}

export function WebHookToJSON(value?: WebHook | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'events': value.events,
        'url': value.url,
        'secret': value.secret,
    };
}


