/* tslint:disable */
/* eslint-disable */
/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface XktChunk
 */
export interface XktChunk {
    /**
     * 
     * @type {string}
     * @memberof XktChunk
     */
    file: string;
}

export function XktChunkFromJSON(json: any): XktChunk {
    return XktChunkFromJSONTyped(json, false);
}

export function XktChunkFromJSONTyped(json: any, ignoreDiscriminator: boolean): XktChunk {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'file': json['file'],
    };
}

export function XktChunkToJSON(value?: XktChunk | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'file': value.file,
    };
}

