/* tslint:disable */
/* eslint-disable */
/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    XktChunkRequest,
    XktChunkRequestFromJSON,
    XktChunkRequestFromJSONTyped,
    XktChunkRequestToJSON,
} from './XktChunkRequest';

/**
 * 
 * @export
 * @interface XktFileRequest
 */
export interface XktFileRequest {
    /**
     * 
     * @type {number}
     * @memberof XktFileRequest
     */
    version: number;
    /**
     * 
     * @type {Blob}
     * @memberof XktFileRequest
     */
    file: Blob;
    /**
     * 
     * @type {Array<XktChunkRequest>}
     * @memberof XktFileRequest
     */
    chunks?: Array<XktChunkRequest>;
}

export function XktFileRequestFromJSON(json: any): XktFileRequest {
    return XktFileRequestFromJSONTyped(json, false);
}

export function XktFileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): XktFileRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'version': json['version'],
        'file': json['file'],
        'chunks': !exists(json, 'chunks') ? undefined : ((json['chunks'] as Array<any>).map(XktChunkRequestFromJSON)),
    };
}

export function XktFileRequestToJSON(value?: XktFileRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'version': value.version,
        'file': value.file,
        'chunks': value.chunks === undefined ? undefined : ((value.chunks as Array<any>).map(XktChunkRequestToJSON)),
    };
}

