/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ZoneSpaceRequest
 */
export interface ZoneSpaceRequest {
    /**
     * 
     * @type {string}
     * @memberof ZoneSpaceRequest
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ZoneSpaceRequest
     */
    longname?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ZoneSpaceRequest
     */
    uuid: string;
}

export function ZoneSpaceRequestFromJSON(json: any): ZoneSpaceRequest {
    return ZoneSpaceRequestFromJSONTyped(json, false);
}

export function ZoneSpaceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ZoneSpaceRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'longname': !exists(json, 'longname') ? undefined : json['longname'],
        'uuid': json['uuid'],
    };
}

export function ZoneSpaceRequestToJSON(value?: ZoneSpaceRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'longname': value.longname,
        'uuid': value.uuid,
    };
}


