version: 2

references:
  container_config: &container_config
    docker:
      - image: circleci/node:12
    working_directory: ~/repo


  restore_npm_cache: &restore_npm_cache
    restore_cache:
      keys:
        - v1-npm-{{ checksum "package.json" }}
        - v1-npm

jobs:
  release:
    <<: *container_config
    steps:
      - checkout
      - *restore_npm_cache
      - add_ssh_keys
      - run:
          name: Avoid hosts unknown for github
          command: echo -e " StrictHostKeyChecking no\n" >> ~/.ssh/config
      - run: npm i --prefix package
      - run: npm run build --prefix package
      - run: npm install --no-save @semantic-release/npm @semantic-release/github conventional-changelog-eslint --prefix package
      - run: npx semantic-release --extends ../config/release.config.js --prefix package
      - save_cache:
          key: v1-npm-{{ checksum "package.json" }}
          paths:
            - package/node_modules/
            - ~/.npm
            - ~/.cache

workflows:
  version: 2
  test_and_release:
    jobs:
      - release:
          context: semantic-release
          filters:
            branches:
              only:
                - master
