version: 2

references:
  container_config: &container_config
    docker:
      - image: circleci/node:12
    working_directory: ~/repo

jobs:
  release:
    <<: *container_config
    steps:
      - checkout
      - add_ssh_keys
      - run:
          name: Avoid hosts unknown for github
          command: echo -e " StrictHostKeyChecking no\n" >> ~/.ssh/config
      - run: npm i --prefix package
      - run: npm run build --prefix package
      - run: npm install --no-save @semantic-release/npm @semantic-release/github conventional-changelog-eslint --prefix package
      - run: cd package && npx semantic-release --extends ./config/release.config.js

workflows:
  version: 2
  test_and_release:
    jobs:
      - release:
          context: semantic-release
          filters:
            branches:
              only:
                - master
