/* tslint:disable */
/* eslint-disable */
/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    PatchedWebHookRequest,
    PatchedWebHookRequestFromJSON,
    PatchedWebHookRequestToJSON,
    WebHook,
    WebHookFromJSON,
    WebHookToJSON,
    WebHookRequest,
    WebHookRequestFromJSON,
    WebHookRequestToJSON,
} from '../models';

export interface CreateWebHookRequest {
    cloud_pk: number;
    WebHookRequest: WebHookRequest;
}

export interface DeleteWebHookRequest {
    cloud_pk: number;
    id: number;
}

export interface GetWebHookRequest {
    cloud_pk: number;
    id: number;
}

export interface GetWebHooksRequest {
    cloud_pk: number;
}

export interface PingWebHookRequest {
    cloud_pk: number;
    id: number;
    WebHookRequest: WebHookRequest;
}

export interface UpdateWebHookRequest {
    cloud_pk: number;
    id: number;
    PatchedWebHookRequest?: PatchedWebHookRequest;
}

/**
 * 
 */
export class WebhookApi extends runtime.BaseAPI {

    /**
     * Create a new Webhook  Required scopes: webhook:manage
     * Create a new Webhook
     */
    async createWebHookRaw(requestParameters: CreateWebHookRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<WebHook>> {
        if (requestParameters.cloud_pk === null || requestParameters.cloud_pk === undefined) {
            throw new runtime.RequiredError('cloud_pk','Required parameter requestParameters.cloud_pk was null or undefined when calling createWebHook.');
        }

        if (requestParameters.WebHookRequest === null || requestParameters.WebHookRequest === undefined) {
            throw new runtime.RequiredError('WebHookRequest','Required parameter requestParameters.WebHookRequest was null or undefined when calling createWebHook.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("BIMData_Connect", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("BIMData_Connect", []);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/cloud/{cloud_pk}/webhook`.replace(`{${"cloud_pk"}}`, encodeURIComponent(String(requestParameters.cloud_pk))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WebHookRequestToJSON(requestParameters.WebHookRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebHookFromJSON(jsonValue));
    }

    /**
     * Create a new Webhook  Required scopes: webhook:manage
     * Create a new Webhook
     */
    async createWebHook(cloud_pk: number, WebHookRequest: WebHookRequest, initOverrides?: RequestInit): Promise<WebHook> {
        const response = await this.createWebHookRaw({ cloud_pk: cloud_pk, WebHookRequest: WebHookRequest }, initOverrides);
        return await response.value();
    }

    /**
     * Delete a webhook  Required scopes: webhook:manage
     * Delete a webhook
     */
    async deleteWebHookRaw(requestParameters: DeleteWebHookRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.cloud_pk === null || requestParameters.cloud_pk === undefined) {
            throw new runtime.RequiredError('cloud_pk','Required parameter requestParameters.cloud_pk was null or undefined when calling deleteWebHook.');
        }

        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling deleteWebHook.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("BIMData_Connect", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("BIMData_Connect", []);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/cloud/{cloud_pk}/webhook/{id}`.replace(`{${"cloud_pk"}}`, encodeURIComponent(String(requestParameters.cloud_pk))).replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a webhook  Required scopes: webhook:manage
     * Delete a webhook
     */
    async deleteWebHook(cloud_pk: number, id: number, initOverrides?: RequestInit): Promise<void> {
        await this.deleteWebHookRaw({ cloud_pk: cloud_pk, id: id }, initOverrides);
    }

    /**
     * Retrieve one configured webhook  Required scopes: webhook:manage
     * Retrieve one configured webhook
     */
    async getWebHookRaw(requestParameters: GetWebHookRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<WebHook>> {
        if (requestParameters.cloud_pk === null || requestParameters.cloud_pk === undefined) {
            throw new runtime.RequiredError('cloud_pk','Required parameter requestParameters.cloud_pk was null or undefined when calling getWebHook.');
        }

        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling getWebHook.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("BIMData_Connect", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("BIMData_Connect", []);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/cloud/{cloud_pk}/webhook/{id}`.replace(`{${"cloud_pk"}}`, encodeURIComponent(String(requestParameters.cloud_pk))).replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebHookFromJSON(jsonValue));
    }

    /**
     * Retrieve one configured webhook  Required scopes: webhook:manage
     * Retrieve one configured webhook
     */
    async getWebHook(cloud_pk: number, id: number, initOverrides?: RequestInit): Promise<WebHook> {
        const response = await this.getWebHookRaw({ cloud_pk: cloud_pk, id: id }, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve all configured webhooks  Required scopes: webhook:manage
     * Retrieve all configured webhooks
     */
    async getWebHooksRaw(requestParameters: GetWebHooksRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<WebHook>>> {
        if (requestParameters.cloud_pk === null || requestParameters.cloud_pk === undefined) {
            throw new runtime.RequiredError('cloud_pk','Required parameter requestParameters.cloud_pk was null or undefined when calling getWebHooks.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("BIMData_Connect", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("BIMData_Connect", []);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/cloud/{cloud_pk}/webhook`.replace(`{${"cloud_pk"}}`, encodeURIComponent(String(requestParameters.cloud_pk))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(WebHookFromJSON));
    }

    /**
     * Retrieve all configured webhooks  Required scopes: webhook:manage
     * Retrieve all configured webhooks
     */
    async getWebHooks(cloud_pk: number, initOverrides?: RequestInit): Promise<Array<WebHook>> {
        const response = await this.getWebHooksRaw({ cloud_pk: cloud_pk }, initOverrides);
        return await response.value();
    }

    /**
     * Trigger a Ping Event sending {\"ok\": true} to the webhook URL. Useful to test your app  Required scopes: webhook:manage
     * Test a webhook
     */
    async pingWebHookRaw(requestParameters: PingWebHookRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<WebHook>> {
        if (requestParameters.cloud_pk === null || requestParameters.cloud_pk === undefined) {
            throw new runtime.RequiredError('cloud_pk','Required parameter requestParameters.cloud_pk was null or undefined when calling pingWebHook.');
        }

        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling pingWebHook.');
        }

        if (requestParameters.WebHookRequest === null || requestParameters.WebHookRequest === undefined) {
            throw new runtime.RequiredError('WebHookRequest','Required parameter requestParameters.WebHookRequest was null or undefined when calling pingWebHook.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("BIMData_Connect", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("BIMData_Connect", []);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/cloud/{cloud_pk}/webhook/{id}/ping`.replace(`{${"cloud_pk"}}`, encodeURIComponent(String(requestParameters.cloud_pk))).replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WebHookRequestToJSON(requestParameters.WebHookRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebHookFromJSON(jsonValue));
    }

    /**
     * Trigger a Ping Event sending {\"ok\": true} to the webhook URL. Useful to test your app  Required scopes: webhook:manage
     * Test a webhook
     */
    async pingWebHook(cloud_pk: number, id: number, WebHookRequest: WebHookRequest, initOverrides?: RequestInit): Promise<WebHook> {
        const response = await this.pingWebHookRaw({ cloud_pk: cloud_pk, id: id, WebHookRequest: WebHookRequest }, initOverrides);
        return await response.value();
    }

    /**
     * Update some field of a webhook  Required scopes: webhook:manage
     * Update some field of a webhook
     */
    async updateWebHookRaw(requestParameters: UpdateWebHookRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<WebHook>> {
        if (requestParameters.cloud_pk === null || requestParameters.cloud_pk === undefined) {
            throw new runtime.RequiredError('cloud_pk','Required parameter requestParameters.cloud_pk was null or undefined when calling updateWebHook.');
        }

        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling updateWebHook.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("BIMData_Connect", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("BIMData_Connect", []);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/cloud/{cloud_pk}/webhook/{id}`.replace(`{${"cloud_pk"}}`, encodeURIComponent(String(requestParameters.cloud_pk))).replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchedWebHookRequestToJSON(requestParameters.PatchedWebHookRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebHookFromJSON(jsonValue));
    }

    /**
     * Update some field of a webhook  Required scopes: webhook:manage
     * Update some field of a webhook
     */
    async updateWebHook(cloud_pk: number, id: number, PatchedWebHookRequest?: PatchedWebHookRequest, initOverrides?: RequestInit): Promise<WebHook> {
        const response = await this.updateWebHookRaw({ cloud_pk: cloud_pk, id: id, PatchedWebHookRequest: PatchedWebHookRequest }, initOverrides);
        return await response.value();
    }

}
